### ISSUE TITLE
Need to keep function  PollLongRunningOperation, in common place for InstanceAdmin and TableAdmin

### ISSUE THREAD

**Issue by roopak-qlogic** [GoogleCloudPlatform/google-cloud-cpp#1017]
Need to keep function  PollLongRunningOperation, in common place for InstanceAdmin and TableAdmin

**Comment by roopak-qlogic** [comment]
Tried to find any existing file where I can fit this API, accessible for both table admin and instance admin, but did not find that, then I started writing new header file with this API as below signature.

template <typename ResultType, ClientType>
    ResultType PollLongRunningOperation(std::shared_ptr<ClientType> client, std::unique_ptr<PollingPolicy> polling_policy ,MetadataUpdatePolicy metadata_update_policy_, google::longrunning::Operation& operation,
                                        char const* error_message,
                                        grpc::Status& status) {
}
But  when I use to call above API from bigtable table admin, I am facing compilation error as below, when client  try to access  GetOperation()  , I tried few approaches but did not get any luck.

error: ‘virtual grpc::Status google::cloud::bigtable::v0::AdminClient::GetOperation(grpc::ClientContext*, const google::longrunning::GetOperationRequest&, google::longrunning::Operation*)’ is protected

may be I am going in wrong direction or missing some small thing, So if  you can suggest something,

**Comment by coryan** [comment]
> error: ‘virtual grpc::Status google:cloud:bigtable::v0::AdminClient::GetOperation(grpc::ClientContext*, const google::longrunning::GetOperationRequest&, google::longrunning::Operation*)’ is protected

I think we fixed those with a suitable application of `friend` in some places.
