### ISSUE TITLE
Implement CacheControl request parameter.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1018]
At the end of this task application developers will be able to specify the `Cache-Control` request header in calls to `ReadObject()`. Even though the parameter is only applicable to anonymous requests:

https://cloud.google.com/storage/docs/json_api/v1/parameters#standard

**Comment by coryan** [comment]
@houglum it seems that setting this header in `Object: insert` does not change the `cacheControl` metadata field. And sending it on `Object: get` (for media) does not seem to have any effect either (the `cacheControl` metadata field seems to override).

Should we implement this header at all?  If so, I am inclined to just test that it is sent by looking at the logs, like we did for `quotaUser`, and leave it at that.  Thoughts?

**Comment by houglum** [comment]
> setting this header in Object: insert does not change the cacheControl metadata field

Hey, you're right.  That's silly.  I could have sworn that wasn't the case, but I was thinking of using gsutil like `gsutil -D -h "Cache-Control: <value>" cp file gs://bucket/obj` -- it's a bit deceptive in that if you look at the request info that `-D` makes it print out, we actually set the object's CacheControl metadata attribute to the value specified on the command line... we don't actually send the header, and it indeed has no effect if you do.  That's... *so intuitive*. /s

> And sending it on Object: get (for media) does not seem to have any effect either (the cacheControl metadata field seems to override).

There's only one case in which supplying this header has any effect, according to [1]:

> You can specify cache-control in a request only for objects that are accessible to all anonymous users.

[1] https://cloud.google.com/storage/docs/json_api/v1/parameters#cachecontrol

**Comment by coryan** [comment]
>> setting this header in Object: insert does not change the cacheControl metadata field

> Hey, you're right. That's silly. 

Should we file a bug?  In the documentation or the service?

**Comment by houglum** [comment]
Probably worth filing against the docs.  I think it's WAI (assuming the goal is to set the CacheControl attribute in the metadata), but should be documented, but should be better documented.

**Comment by coryan** [comment]
I am closing this bug, there is no reason to implement this control if it has no effect.
