### ISSUE TITLE
Add upsert_*() convenience functions for ObjectMetadata and BucketMetadata

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1046]
Both `ObjectMetadata` and `BucketMetadata` have a map of (key,value) pairs for arbitrary annotations. We should add a convenience function `upsert_metadata` and `upsert_labels` so application developers do not have to write chained calls like `mutable_medata().emplace_back()`.  We already have convenience functions to delete key value pairs and check their presence and/or values, we just need a modifier.

**Comment by frankyn** [comment]
@coryan, is upsert_* familiar in C++? I like not having chained methods with this approach, but concerned with the name.

**Comment by coryan** [comment]
Frankly no, `upsert_` is not used in the standard library.  The problem is that the `std::map<K,V>` template class has a ton of different member functions with slightly different semantics:

- `map[k] = v` updates and/or inserts the value.
- `map.insert(k, v)` copies `k` and `v`, inserts if it does not exit and leaves the map unchanged if `k` was already there.  It returns a tuple to help you figure out what happened.
- `map.emplace(k, v)` is similar, but uses move semantics, which is unfortunate because it destroys `v` even when the insertion fails.
- `map.try_emplace(k, v)` solves the problem of the destroyed `v` in C++17.
- `map.emplace_hint(i, k, v)` is like emplace but takes a hint on the location, which is handy because you can use the result of a previous `map.find()` to save a lookup, effectively making a lookup + insert O(ln(n)) instead of 2 * O(ln(n)).  
- `map.insert(i, map::value_type(k, v))` is like the previous one with a hint too.

In fact, there are 5 overloads of `insert()` in C++11 and 10 overloads in `C++17`, plus 4 overloads in `try_emplace`, and `emplace` and `emplace_hint`. 

As I see it, we should provide a few convenience functions for the most common cases, using BucketMetadata for example:

- `has_label` - test for existence.
- `label()` - get value if it exists, fails otherwise.
- `upsert_label()` - update or insert the value.

and then we should provide `mutable_labels()` as a escape hatch where the developer gets access to the full list of overloads available in the language, with the downside of having to chain them.
