### ISSUE TITLE
Implement integration test for Snapshot CRUD operations

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1052]
We need an integration test in the style of:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/305f193b24bd40e35fc9b7a1085d9e9ce2fb4805/google/cloud/bigtable/tests/instance_admin_integration_test.cc#L124

To test the CRUD operations for snapshots: ListSnapshots(), CreateSnapshot(), GetSnapshot(), and DeleteSnapshot.

**Comment by mbrukman** [comment]
@roopak-qlogic, @coryan — since PR #1100 was merged, should this issue be closed? Or are there other tasks remaining?

**Comment by coryan** [comment]
I think this is fixed.
