### ISSUE TITLE
Create an integration test for CheckConsistency* functions.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1054]
We need an integration test that creates a table (which may need to be replicated), then calls `TableAdmin::GenerateConsistencyToken()`, and later calls `TableAdmin::CheckConsistency` (and/or `TableAdmin::WaitForConsistencyCheck`) until the consistency is achieved.

**Comment by manish-qlogic** [comment]
@coryan 

> We need an integration test that creates a table (which may need to be replicated)

can we make assumption that instance passed as an argument to integration test uses replication (multiple clusters)?

**Comment by coryan** [comment]
Yes. Please check (using `ListClusters()`) at the beginning of the integration test, and printing a nice error message when the condition is not met.

**Comment by manish-qlogic** [comment]
>Yes. Please check (using ListClusters()) at the beginning of the integration test, and printing a nice error message when the condition is not met.

`CheckConsistency` is from `TableAdmin` where as `ListClusters` is part of `InstanceAdmin`, we haven't used both `TableAdmin` and `InstanceAdmin` in a single integration test till now. So should I create a bigtable_client_common_integration_test which would use both. This way `CheckConsistency` test case and even the `SnapshotTable` integration tests can be run against production without assuming existence of instances and clusters.
