### ISSUE TITLE
Implement a sample snippet for TableAdmin::GetSnapshot.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1055]
The snippet should be linked from the Doxygen documentation in `google/cloud/bigtable/table_admin.h`, it should be compiled and executed as part of the CI builds, but should not run against production in each commit or PR.

**Comment by coryan** [comment]
> Need to understand , all snapshot examples can we run against emulator, if not then can we use example code snippet as a doxygen comment in table_admin.h.

Let me try to answer that, though I may have misread it:

> all snapshot examples can we run against emulator,

Actually we cannot, the emulator has bugs (GoogleCloudPlatform/google-cloud-go#1135) that prevents us from using it for the examples and/or integration tests.

> if not then can we use example code snippet as a doxygen comment in table_admin.h.

We can use the example code as snippets even if they do not work in the emulator.  Please do test them against production at least once.

**Comment by sduskis** [comment]
@coryan, can we close this?

**Comment by coryan** [comment]
Yup.
