### ISSUE TITLE
SSL locking callbacks, retain if already installed?

### ISSUE THREAD

**Issue by ameihm0912** [GoogleCloudPlatform/google-cloud-cpp#1070]
I came across #1050 which appears recently added

Based on a quick pass it looks like this will install the locking callbacks based on the library versioning.

Before calling `CRYPTO_set_locking_callback`, would it be worthwhile here to add a call to `CRYPTO_get_locking_callback` to see if callbacks are already present? If they are, just skip setting them up?

This for example will preserve any functions already installed as a callback by the main application that includes the library, instead of overwriting. This also helps with scenarios like dynamic shared object loading, since if it is implicitly installed it will overwrite any existing callback when the library is opened and used, and if the library is later closed the callback function pointer will reference invalid memory.

**Comment by coryan** [comment]
Thanks, that makes total sense and simpler than what i had in mind.
