### ISSUE TITLE
Split TableAdmin samples out of bigtable_samples.cc

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1107]
We should split the examples related to `bigtable::TableAdmin` to its own file. We should also change the samples to use the style followed in the Google Cloud Storage examples, i.e.:

- The `main()` function just parses the command (the name of the example) to execute.
- The `main()` function passes `argc` and `argv` to a function that implements the example.
- The function parses `argc` and `argv` and calls a lambda with those arguments.
- Only the body of the lambda is reference in the Doxygen snippet.

To see how this works look here:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/58b603dfa10b58303eeb259ea749d1ba7473fa40/google/cloud/storage/examples/storage_bucket_samples.cc#L68

That design is far more flexible, it allow you to have different number of arguments for each example, and the lambda can show the expected types for the arguments.

That would make PRs like #1103 much easier to write.

**Comment by roopak-qlogic** [comment]
I would like to confirm my understanding as below 
following examples should move to new file  table_admin_samples.cc 

CreateTable, ListTables, GetTable, DeleteTable, ModifyTable, DropAllRows, DropRowsByPrefix, Apply, BulkApply, ReadRow, ReadRows, ReadRowsWithLimit, CheckAndMutate, ReadModifyWrite, SampleRows, SampleRowsCollections, RunTableOperations, RunFullExample.

following examples should be written in existing file  bigtable_samples.cc 
WaitForConsistencyCheck, CheckConsistency, ListSnapshots, GetSnapshots, DeleteSnapshot, CreateTableFromSnapshot

Above both files should follow the style as per 
google-cloud-cpp/google/cloud/storage/examples/storage_bucket_samples.cc

**Comment by coryan** [comment]
> I would like to confirm my understanding as below
following examples should move to new file table_admin_samples.cc

I would suggest you call that `table_admin_snippets.cc` because we have 3 cases: 

> CreateTable, ListTables, GetTable, DeleteTable, ModifyTable, DropAllRows, DropRowsByPrefix,

I think these belong in the new `table_admin_snippets.cc`

> Apply, BulkApply, ReadRow, ReadRows, ReadRowsWithLimit, CheckAndMutate, ReadModifyWrite, SampleRows, SampleRowsCollections,

I think these belong in a new file maybe `data_admin_snippets.cc`?

> RunTableOperations, RunFullExample.

We should probably leave these where they are.

following examples should be written in existing file bigtable_samples.cc

> WaitForConsistencyCheck, CheckConsistency, ListSnapshots, GetSnapshots, DeleteSnapshot, CreateTableFromSnapshot

Hmmm, I think these belong in `table_admin_snippets`, right?

> Above both files should follow the style as per
google-cloud-cpp/google/cloud/storage/examples/storage_bucket_samples.cc

The snippets files should.

This is going to be a big change.  Please split it in multiple PRs.  I recommend you start with one of the two snippet files and move *one* example first. Then we move all the examples for that file, then we proceed with the other files.
