### ISSUE TITLE
Fix install directory target for headers google/cloud/storage/CMakeLists.txt

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1179]
It says `blah/blah/client` which is obviously wrong I think it works due to the top-level CMake installing all the headers, which may be its own problem too.

**Comment by perfinion** [comment]
I noticed this too when I was fixing up the cmake stuff, pretty sure its cuz of the "*.h" here: https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/05bab87035440301fc3f600596f8e627961ea614/google/cloud/CMakeLists.txt#L161-L163

They are currently "correct" in that `for i in $(find /tmp/cloud/usr/include -iname "*.h"); do g++ -o/dev/null -E -I/tmp/cloud/usr/include $i || echo $i; done` returns cleanly but ideally yes the top level should not double-install things
