### ISSUE TITLE
Implement (sync) Table::Apply(SingleRowMutation)

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#12]
At the end of this task `bigtable::Table` will provide an `Apply()` member function to apply mutations to a single row.  The member functions should:

* Use the policies in effect to retry any recoverable RPC failures.
* Use the policies in effect to determine if a mutation is idempotent.
* Report an error when the operation fails after the policies "give up".

**Comment by coryan** [comment]
For what is worth, this is blocked behind #13, #14, #15 and #16.

**Comment by coryan** [comment]
#13, #14, and #16 are done.  I just closed #15 as invalid.  I am calling this done.

**Comment by mbrukman** [comment]
@coryan — replaced the bulletted list in the issue description with checkboxes and added issue references; PTAL and verify if my mapping is correct.

**Comment by coryan** [comment]
Nice, thanks.  LGTM.
