### ISSUE TITLE
Document "Use the features to simplify reading bigendian64 values from Cloud Bigtable."

### ISSUE THREAD

**Issue by manish-qlogic** [GoogleCloudPlatform/google-cloud-cpp#1214]
This is sub-task of #454.

"Use the features to simplify reading bigendian64 values from Cloud Bigtable."

**Comment by manish-qlogic** [comment]
@coryan 

This is also closed with #1199, we have an example in [bigtable-samples-data-client.dox](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/1ea90ead526cc25aaa1a3da87bd95bc4dbee8545/google/cloud/bigtable/doc/bigtable-samples-data-client.dox#L34) file to demonstrate simplified reading of bigendian64 values.

**Comment by coryan** [comment]
@manish-qlogic you are correct. Closed in #1199.
