### ISSUE TITLE
Document how service account credentials work.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1241]
The documentation of our classes should describe how they work and/or reference existing documentation that does (maybe an introduction to Oauth2?)

**Comment by manish-qlogic** [comment]
@coryan 

We documented use of Credential classes [here](https://github.com/GoogleCloudPlatform/google-cloud-cpp/issues/137#issuecomment-406147064)

Should we include this information on landing page or Bigtable?

**Comment by coryan** [comment]
I think we are done with this.  The various classes in `google/cloud/storage/oauth2` reference the right documentation, and the documentation of `google::cloud::storage::Client` links to those classes.

I am closing this, if you think something is missing please reopen.
