### ISSUE TITLE
Implement noex::InstanceAdmin::AsyncUpdateAppProfile.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1271]
This is not a typical async unary RPC. This function should use the polling policy to periodically query the long running operation, once successful (or once the policy expires) it should call the callback that the application provides. The function should use timers in the completion queue to wait before polling again.

The first step is to propose the API in the bug, once approved, you must:

- [ ] Implement this new function.
- [ ] Implement an integration test for this new function.

**Comment by roopak-qlogic** [comment]
Here I am thing that, API should be like   
template <typename Functor,
            typename std::enable_if<
                google::cloud::internal::is_invocable<
                    Functor, CompletionQueue&, google::longrunning::Operation&,
                    grpc::Status&>::value,
                int>::type valid_callback_type = 0>
  void AsyncUpdateAppProfile(bigtable::InstanceId const& instance_id,
                             bigtable::AppProfileId profile_id,
                             AppProfileUpdateConfig config, CompletionQueue& cq,
                             Functor&& callback)

**Comment by coryan** [comment]
Reformatting your proposal this looks like:

```C++
template <typename Functor>
void AsyncUpdateAppProfile(
    bigtable::InstanceId const& instance_id,
    bigtable::AppProfileId profile_id,
    AppProfileUpdateConfig config, CompletionQueue& cq,
    Functor&& callback)

typename std::enable_if<
    google:cloud:internal::is_invocable<Functor, CompletionQueue&, google::longrunning::Operation&,
    grpc::Status&>::value
```

I do not think this is what we want, the application would then need to poll that long running operation, potentially asynchronously, to figure out the result.

I think you should read more like this:

```C++
template <typename Functor>
void AsyncUpdateAppProfile(
    bigtable::InstanceId const& instance_id,
    bigtable::AppProfileId profile_id,
    AppProfileUpdateConfig config, CompletionQueue& cq,
    Functor&& callback) {

  intermediate = [callback](CompletionQueue& cq, google::longrunning::Operation& op,
    grpc::Status& status) {
    // start polling "op" using the polling policy... call "callback" when the polling succeeds.
  }
  return AsyncRetryBlah(..., intermediate);
}

typename std::enable_if<
    google:cloud:internal::is_invocable<Functor, CompletionQueue&,
    /* whatever the polling operation returns */&,
    grpc::Status&>::value

```

That is, this function should first make an asynchronous request to start the update, when that succeeds it should start a polling loop, and then invoke the callback with the actual result when the polling succeeds.

/cc: @dopiera because he was interested in refactoring that polling loop.

**Comment by dopiera** [comment]
It's likely that it will be very similar to #1472
