### ISSUE TITLE
Implement noex::Table::AsyncReadRow.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1277]
Model this as a typical async unary RPC call. It probably should be implemented **after** `AsyncReadRows`.

First propose an API for the function, once approved, you must implement both:

- [ ] An integration test that uses this function.
- [ ] The function itself.

**Comment by manish-qlogic** [comment]
@coryan 

I am thinking of implementing `AsyncReadRow` same as `AsyncReadRows` with following changes

1. `AsyncReadRow` will make use of `MakeUnaryStreamRpc` just like `AsyncReadRows`. 
2. row_limit will be hard coded to 1.
3. unlike `ReadRowCallbcak` and `DoneCallback` in `AsyncReadRows`,  `AsyncReadRow` will have a single functor and return the response by means of `AccumulatedResult`. The API will look like

```
  template <typename Functor,
            typename std::enable_if<
                google::cloud::internal::is_invocable<
                    Functor, CompletionQueue&, std::pair<bool, Row>&,
                    grpc::Status&>::value,
                int>::type valid_callback_type = 0>
  std::shared_ptr<AsyncOperation> AsyncReadRow(RowSet row_set, Filter filter,
                                                 CompletionQueue& cq,
                                                 Functor&& callback, bool raise_on_error = false) {
```

4. New classes `AsyncReadRowOperation` and  `AsyncReadRow` to process gRPC response, accumulate result and return a single row via callback.

Please suggest.
