### ISSUE TITLE
Change Change AsyncRetryOp<> to derive from AsyncOperation

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#1305]
Per the discussion in #1289, we want to allow application developers to cancel asynchronous operations.

If the application requests a cancelation then the `Cancel()` operation should:

- [ ] Set the state of the class so not new requests are issued.
- [ ] Cancel the currently pending operation, the current timer if there is one, or the current asynchronous request.
- [ ] When the pending operation cancels (or succeeds) signal the result to the application via the callback.

**Comment by dopiera** [comment]
Fixed in #1388.
