### ISSUE TITLE
Implement integration test for TableAdmin::DropRows*() against the Cloud Bigtable Emulator

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#141]
We need to have #32 completed before we can write a useful integration test for `TableAdmin::DropRowsByPrefix()` and `TableAdmin::DropAllRows()`, this issue is to track the missing integration tests only.

**Comment by hemant-qlogic** [comment]
Integration test for only these functions TableAdmin::DropRowsByPrefix() and TableAdmin::DropAllRows() is required? 
No other function from TableAdmin class?

**Comment by coryan** [comment]
Correct.  There are already integration tests for the other functions in TableAdmin:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/master/bigtable/tests/admin_integration_test.cc#L115

If you are curious, we wrote those when `ReadRows()` was not implemented so it was not possible to write integration tests for `Drop*Rows*` at that time.

**Comment by hemant-qlogic** [comment]
For this point I made some changes in the admin_integration_test.cc, like variable naming, test case naming, used common functions from table_integration_test.cc

**Comment by coryan** [comment]
Fixed in #289, I typed the magical "fixes" string incorrectly.
