### ISSUE TITLE
Reconnect AdminClient and DataClient when a UNAVAILABLE error is received.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#145]
An UNAVAILABLE error indicates that the server responded with a GOAWAY http message.  We need to reset the channel used for the server when that happens.  This should probably be implemented after #144.

**Comment by garye** [comment]
That's not always true. There are cases today where `UNAVAILABLE` is returned for unrelated reasons.

**Comment by coryan** [comment]
Is there a better way to know when the client gets a GOAWAY message?  Or when it needs to recreate the channel?  The documentation around this stuff is rather awful, e.g.:

**Comment by coryan** [comment]
Okay, seems like this would be a waste of time, the documentation here:

https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md

says that the `Channel` should handle reconnections on a `GOAWAY` frame.

**Comment by coryan** [comment]
Closing because it is not a real issue, gRPC handles this for us.
