### ISSUE TITLE
Decide on a synchronization/parallelism strategy for credential refreshes.

### ISSUE THREAD

**Issue by houglum** [GoogleCloudPlatform/google-cloud-cpp#1457]
Documenting this as part of the discussion in #1452.

The credential code in that PR calls `Refresh()` with the mutex held. That means that once the credential has expired, if multiple requests are invoked on the storage `Client` at the same time, they will all hang until one of them (done serially, due to the locking) successfully refreshes the credentials.

Cons to this approach:
*  All the threads wait and burn time that could be used for some other purpose.
*  If we're in a state where a small percentage of oauth2 requests are failing, encountering one of those failures results in all the threads waiting

Pros to this approach:
*  We don't hammer the oauth2 service.  I *assume* that in most failure cases, something has actually briefly gone wrong, and we do want to utilize the (default) exponential backoff strategy to give the service an opportunity to fix the issue.

As mentioned by @coryan, here are some possible alternatives:
*  Just have all the threads refresh; the first one that gets a response "wins" and updates the token.
   *  Con: wasteful; we spam the oauth2 service and end up throwing away every result except the first successful one.  
   *  Pro: Potentially saves time in the case where a small percentage of oauth2 requests are failing; each thread sends a refresh request in parallel, and we take the first success we get.
*  If one thread is trying to refresh and the token is not really expired, we are refreshing because we have that slack period between "safe" expiration and actual expiration; just reuse the current token (even though it's close to expiring) while the other thread has the lock and is performing a refresh.

**Comment by houglum** [comment]
I think the existing approach presents less surprising behavior and and straightforward code paths.  It's certainly easier to reason about from a debugging standpoint (like when looking through logs and seeing when a token was used/refreshed).

@coryan unless you have any strong objections, I'll decide to stick with the existing behavior and will close this.

**Comment by coryan** [comment]
SGTM.
