### ISSUE TITLE
Compilation issue with MSVC 15.8 (use of `_byteswap_ushort` in constexpr context)

### ISSUE THREAD

**Issue by ras0219-msft** [GoogleCloudPlatform/google-cloud-cpp#1559]
### What version of `google-cloud-cpp` are you using?

v0.3.0

### What compiler and version are you using?

MSVC 15.8

### What were you trying to do?

Compile :)

### Further description

1. On MSVC, `google/cloud/internal/getenv.cc` uses `std::unique_ptr<>` but does not include `<memory>`. This won't currently repro in 15.8, however it's an obvious "improvement" so please consider fixing it :)
2. On MSVC, `google/cloud/internal/big_endian.h` uses `_byteswap_ushort` (et al) in `constexpr` contexts which they are not defined to support; I'll file a bug internally to look into adding it, however it does not work in 15.8

Repro for the second case: https://godbolt.org/z/-9O1mJ

**Comment by coryan** [comment]
This is now fixed in `master`.  Also:

> What were you trying to do?
> Compile :)

Was too funny, thanks!
