### ISSUE TITLE
Implement bigtable::RowReader::Cancel()

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#179]
This function is declared, but not implemented or tested.  At the end of this task the function should exist and be able to cancel a stream safely.  Please note that gRPC requires one to read all the elements of the stream before calling `Finish()`.

**Comment by DanielMahu** [comment]
Right, I think this should do something like:
```
context_->TryCancel();
// Also drain any data left unread
ReadRowsResponse response;
while (stream_->Read(&response)) {
}
stream_->Finish();  // should ignore errors? probably
```

**Comment by coryan** [comment]
That sounds about right.  I assume you will send a PR?

**Comment by DanielMahu** [comment]
Yup, working on it.

**Comment by DanielMahu** [comment]
This came up in https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/182#discussion_r161870676 and will be addressed here: to avoid leaks, RowReader needs to make sure `Finish()` is properly called on all streams; which I think amounts to keeping track of this and adding a `Cancel()` call in the destructor.
