### ISSUE TITLE
Create a build with libc++ on Linux

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#184]
[libc++](https://libcxx.llvm.org/) is (in some respects) a more strict implementation of the standard C++ library than the stock libstdc++ included in most Linux distributions.  Currently the only build that uses libc++ is the macOS build, which is fairly slow, excluded from PRs, and thus problems can go undetected for a while (see #183).  If we can configure a build on Linux with Clang and libc++ then these problems would be detected earlier, and we would have higher confidence that the macOS build would succeed.

For what is worth, Fedora has packages for libc++ under `libcxx-devel` and `libcxxabi-devel`.

**Comment by remyabel** [comment]
I decided to tackle this but I've run into a couple of issues:

- I presumed that the new GCC ABI would be compatible with libc++, yet when trying to link googletest it complains about `std::string` errors. So either my assumption is wrong or I'm missing something w.r.t. googletest

- CMake doesn't seem to have a clean way to switch standard libraries. So I resort to `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++ -lc++abi")` and `CMAKE_FLAGS="${CMAKE_FLAGS} -DCMAKE_CXX_FLAGS=\"-stdlib=libc++\""`. the latter is undesirable since overriding `CMAKE_CXX_FLAGS` manually is considered an anti-pattern these days and the former isn't exactly clean

Furthermore, I pair this with `TEST_INSTALL=yes` to make sure the dependencies get compiled with `libc++`. However, another build failure happens with `grpc`:

```
/usr/bin/ld: CMakeFiles/grpc_ruby_plugin.dir/src/compiler/ruby_plugin.cc.o:
(.data.rel.ro._ZTV17RubyGrpcGenerator[_ZTV17RubyGrpcGenerator]+0x28): undefined reference to
 `google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor
 const*, std::allocator<google::protobuf::FileDescriptor const*> > const&,
 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&,
 google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char,
 std::char_traits<char>, std::allocator<char> >*) const'
# ...snip...
```

I wonder if `-D_GLIBCXX_USE_CXX11_ABI=1` is necessary here, but I'm sure my approach is flawed.

**Comment by coryan** [comment]
@remyabel I have assigned this to you for the time being, we can clear that at any time.

One thing to try is to build with Bazel, which is better at doing hermetic builds and compiling all the dependencies with the same compiler options.  The Bazel scripts would need some non-trivial changes I expect.

If we are using CMake: one thing to keep in mind is that building with external projects (aka `TEST_INSTALL=no`) or with pre-installed packages involves calling completely separate invocations of CMake.  Setting flags like `CMAKE_CXX_FLAGS` in our `CMakeLists.txt` file would have no effect in the invocations to build gRPC, protobuf, or googletest. I believe we will need to resort to environment variables so all the CMake invocations get these flags (yuck).

**Comment by remyabel** [comment]
> Setting flags like CMAKE_CXX_FLAGS in our CMakeLists.txt file would have no effect in the invocations to build gRPC, protobuf, or googletest

No, I'm actually setting `CMAKE_FLAGS` inside `build_docker.sh`. Generally overriding an external project's `CMAKE_CXX_FLAGS` is bad practice but I don't see an easier approach short of patching those projects.

**Comment by remyabel** [comment]
Ah, I'm blind. I didn't see:

      -DgRPC_CARES_PROVIDER=package \
      -DgRPC_PROTOBUF_PROVIDER=package \

So it wasn't linking against the thing I just compiled. I will avoid using `TEST_INSTALL` then.

**Comment by remyabel** [comment]
Update on this. I decided to scrap my flawed approach and do something like the following. For each external dependency I just add to the import targets:

```cmake
if (USE_LIBCXX)
    set_property(TARGET GTest::gmock
                 APPEND
                 PROPERTY INTERFACE_COMPILE_OPTIONS
                          "-stdlib=libc++")

    set_property(TARGET GTest::gmock
                 APPEND
                 PROPERTY INTERFACE_LINK_LIBRARIES
                          "c++abi")
    # etc.
endif ()
```

This seems to do the job pretty well. The only outliers are OpenSSL and NlohmannJson judging from the error messages I'm getting.

**Comment by coryan** [comment]
Have you considered adding these options to the `google_cloud_cpp_common_options` library?  It is a pure `INTERFACE` that all targets should link into, and therefore all targets "inherit" whatever options you add to `google_cloud_cpp_common_options`.

OpenSSL is a pure C library, and NlohmannJson is a pure header library.

**Comment by remyabel** [comment]
Yes, I had that as well. Something like:

```cmake
function (google_cloud_cpp_add_common_options target)
  # ...
  if (USE_LIBCXX)
    target_compile_options(${target} INTERFACE "-stdlib=libc++")
  endif ()
endfunction() 
```

Then:

```cmake
target_link_libraries(google_cloud_cpp_common
                      PUBLIC Threads::Threads
                             $<$<BOOL:${USE_LIBCXX}>:c++abi> # or INTERFACE
                      PRIVATE google_cloud_cpp_common_options)
```

I understand that INTERFACE dependencies are supposed to be transitive, but there are issues somewhere.
