### ISSUE TITLE
Include "google-cloud-resource-prefix" metadata header in each request.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#190]
The client should append this to the metadata in the `grpc::ClientContext` for each request (use [AddMetadata](https://grpc.io/grpc/cpp/classgrpc_1_1_client_context.html)).  It should refer to the Cloud Bigtable instance that is being operated on, e.g., `projects/my-project/instances/my-instance`.

See the Go [code](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/f0465ad6918918679c20f23e5340db438d73dea6/bigtable/admin.go#L89) for an example.

**Comment by coryan** [comment]
Also use the `x-goog-request-params` header.

**Comment by coryan** [comment]
@manish-qlogic before you start coding on this one please write down the proposed design.  It can be a short markdown document, or a comment in this header.  I am mostly interested in knowing:

* Where (what class, function, or component) will implement the functionality?  Can we avoid sprinkling this code in each API?
* How will we test this?  Are unit tests possible?  Are integration tests possible?

**Comment by manish-qlogic** [comment]
**Approach 1**
_Use of `bigtable::ClientOptions` to store metadata_
1. metadata will be stored inside client_options like endpoint and credentials. This 
will inturn moved/stored in `common_client.h`. 
change in `client_options.h, client_options.cc and comman_client.h.`
2. Need to introduce createDefaultClientContext in `CommonClient` to get default 
grpc::ClentContext with metadata.
3. table_admin[.cc|.h] and data_client[.cc|.h] will be enhanced to createDefaultClientContext.

**Approach 2**
_rpc_retry_policy like approach_
1. A MetaDataHolder class willbe created and it will retain key,value pair there. 
2. use setup method of new class to set client context in table_admin[.CC|.h] and 
data_client[.CC|.h] classes.

**Approach 3**
1. introduce MetaDataHolder and pass it as an additional argument from admin_client 
and data_client.
2. MetaDataHolder class then can be used to generate initialClientContext.

**Testing**
Unit testing can be completed using mocks but not sure of integration tests

**addional**
I think rec_retry_policy.h is not needed in bulk_mutator.cc, it can be removed.

**Comment by manish-qlogic** [comment]
@coryan  [;ease provide feedback.

**Comment by coryan** [comment]
Thanks for doing the research.  I think **Approach 1** is not workable because we want the `CommonClient` to be usable for multiple tables.  I think **Approach 2** works, the `Table` and `TableAdmin` classes will need to hold one of these objects, and initialize them once.  I think **Approach 3** is suspect (not sure if it works or not, would need to see code), but extra arguments are not a "good thing".

Let's go with **Approach 2**.

For the integration tests: we can use an embedded server, like the one in the `bigtable/benchmarks/` directory to verify the requests include the right metadata.  But again, the unit tests kind of cover that, so maybe they would be redundant.  I propose that your write the unit tests and then we decide.

**Comment by manish-qlogic** [comment]
@coryan 

> Also use the x-goog-request-params header.

would x-goog-request-params be part of metadata in ClientContext?

if yes, will it contain a single key value pair or multiple pairs?

**Comment by coryan** [comment]
> would x-goog-request-params be part of metadata in ClientContext?

Yes.

> if yes, will it contain a single key value pair or multiple pairs?

As far as I can tell a single key value pair.  Let's start there and change it later if we need to.

**Comment by coryan** [comment]
1. `ListInstances()` should just send `projects/<project_id>` in google-cloud-resource-prefix.

1. There is no default value for `x-good-request-params`, if we do not know what to set it to, just do not set it.

I think in general this is what we want:

| Class Name | x-goog-request-params value | google-cloud-resource-prefix value | accessor | 
| :-------------- | :---------------------------------------- | :--------------------------------------------- | :------------ |
| `InstanceAdmin` | `project=projects/<project_id>` | `projects/<project_id>` | `project_name()` |
| `TableAdmin` | `instance=projects/<project_id>/instances/<instance_id>` | `projects/<project_id>/instances/<instance_id>` | `instance_name()` |
| `Table` |  `instance=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `table_name()` |

Please let me know if I missed anything.

**Comment by igorbernstein2** [comment]
I don't think that quite right. The key of `x-goog-request-params` must match the attribute in the request proto.

So for data operations it would be `table_name =projects/<project_id>/instances/<instance_id>/tables/<table_id>`.

For CreateTable it would be `parent=projects/<project_id>/instances/<instance_id>`

For GetTable it would be `name=projects/<project_id>/instances/<instance_id>/tables/<table_id>`

**Comment by igorbernstein2** [comment]
Also, I don't think it's necessary to implement both `x-goog-request-params value` and `google-cloud-resource-prefix`.

**Comment by coryan** [comment]
> Also, I don't think it's necessary to implement both `x-goog-request-params` value and
> `google-cloud-resource-prefix`.

Which one would you suggest we go with?

**Comment by coryan** [comment]
@manish-qlogic please see the new table based on @igorbernstein2 comments.

| Member Function | x-goog-request-params value | google-cloud-resource-prefix value | accessor | 
| :-------------- | :---------------------------------------- | :--------------------------------------------- | :------------ |
| `InstanceAdmin::ListInstances` | `parent=projects/<project_id>` | `projects/<project_id>` | `project_name()` |
| `TableAdmin::CreateTable` | `parent=projects/<project_id>/instances/<instance_id>` | `projects/<project_id>/instances/<instance_id>` | `instance_name()` |
| `TableAdmin::ListTables` | `parent=projects/<project_id>/instances/<instance_id>` | `projects/<project_id>/instances/<instance_id>` | `instance_name()` |
| `TableAdmin::GetTable` | `name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>` | None, part of request. |
| `TableAdmin::DeleteTable` | `name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>` | None, part of request. |
| `TableAdmin::ModifyColumnFamilies` | `name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>` | None, part of request. |
| `TableAdmin::DropRowRange` | `name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>` | None, part of request. |
| `Table::ReadRows` |  `table_name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `table_name()` |
| `Table::SampleRowKeys` |  `table_name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `table_name()` |
| `Table::Apply` |  `table_name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `table_name()` |
| `Table::BulkApply` |  `table_name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `table_name()` |
| `Table::CheckAndMutateRow` |  `table_name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `table_name()` |
| `Table::ReadModifyWriteRow` |  `table_name=projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `projects/<project_id>/instances/<instance_id>/tables/<table_id>` | `table_name()` |

**Comment by igorbernstein2** [comment]
I rolled out the new style of headers on the serverside yesterday. So you should be good to go on using the new x-goog-request style. The mapping for all autogen clients was added here:
https://github.com/googleapis/googleapis/commit/de4a5ff6534892029e083d7c0651e06e98c51729

Feel free to drop the old ones.
