### ISSUE TITLE
Convert bigtable/tests/data_integration_test to use googletest

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#194]
As described in #153, using the framework for integration tests works well.

**Comment by DanielMahu** [comment]
I have a work in progress on this issue that I ended up doing while on the ReadRows integration tests (#77), it's at https://github.com/DanielMahu/google-cloud-cpp/tree/integration-data.

**Comment by coryan** [comment]
I am assigning this to you then, since you have already started on it.
