### ISSUE TITLE
Implement connection pools for bigtable::DataClient

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#204]
We want a mechanism for the user to control how many connections are inside the `bigtable::DataClient`, and for the library to round-robin between the connections.  Or even better, do some clever throughput or latency based load balancing between the connections.

The reason for this is that each connection to bigtable.googleapis.com has limits on the number of pending operations, so more connections == more pending ops == better throughput.

**Comment by sduskis** [comment]
The Data client needs the connection pool.  The Admin client ought be be used in low throughput scenarios.

**Comment by coryan** [comment]
You are right, of course, I typed exactly the opposite of what I meant.
