### ISSUE TITLE
Create one integration test for each mutation factory functions.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#206]
In `bigtable/client/mutations.h` we have multiple factory functions, i.e.:

- [ ] `bigtable::SetCell(family, column, timestamp, value)`
- [ ] `bigtable::SetCell(family, column, value)`
- [ ] `bigtable::DeleteFromColumn()`
- [ ] `bigtable::DeleteFromColumnStartingFrom()`
- [ ] `bigtable::DeleteFromColumnEndingAt()`
- [ ] `bigtable::DeleteFromFamily()`
- [ ] `bigtable::DeleteFromRow()`

We need to write an integration test for each one, much like we did for `bigtable::Filter::*`.

**Comment by hemant-qlogic** [comment]
There is a file mutations_test.cc, where all the mentioned test cases are covered.
Do I need to do any changes in those test cases?

**Comment by coryan** [comment]
No need to change `mutations_test.cc`.  That is a unit test, we need an integration test like `bigtable/client/filters_integration_test.cc` where we verify that using these operations against the Cloud Bigtable Emulator has the desired effect.

**Comment by hemant-qlogic** [comment]
PTAL
