### ISSUE TITLE
Create a build for Windows 64 using appveyor

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#23]
At the end of this task we will have a CI build for appveyor using Windows 64.  There is some prior art for things using protobuf + grpc in:

https://github.com/coryan/cpp-docs-samples

**Comment by coryan** [comment]
For a much better setup with appveyor look at:

https://github.com/google/googletest/blob/master/appveyor.yml

**Comment by paprat** [comment]
What are the platforms are we looking to support for this client (windows platform point of view)?

**Comment by coryan** [comment]
I think we should go for x86_64, which I believe the Windows folks call "Win64".  For compilers, start with whatever it is easiest "Visual Studio 15 2017" seems like a good initial guess.

**Comment by coryan** [comment]
Any news on this front?  Do you need us to review some code or configurations (even early drafts)?

**Comment by paprat** [comment]
It is in progress. I am receiving an error in build phase after installation. I am trying to resolve but if I am unable to do this I will ask you guys.

**Comment by coryan** [comment]
Any news?  Can we help you with anything?

**Comment by coryan** [comment]
Ooops, clicked the wrong button.
