### ISSUE TITLE
Abseil and installed libraries

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#232]
[Abseil](https://abseil.io) does not provide, nor are they planning to provide a `make install` target.  The details are in abseil/abseil-cpp#38 and their [compatibility promises](https://abseil.io/about/compatibility).  We have four choices:

1. Use Abseil and do not install the bigtable libraries: our users will either need to compile from source, or will need to manually install things.

1. Use Abseil punt on how it gets installed, and provide install targets for the bigtable libraries: we will provide install targets for the bigtable libraries, but the users will need to install Abseil manually.

1. Use Abseil and install the bigtable libraries and Abseil with ugly hacks: we will provide our own `make install` for Abseil, and our own `make install` for bigtable libraries.

1. Do not use Abseil: we can provide install targets, the library is easy to use but we will need to write replacements for: `absl::make_unique` (used 46 times), `absl::string_view` (used 23 times), `absl::StrCat()` (15 times), `absl::StrJoin()` (5 times),  `absl::optional<>` (5 times), `absl::FromChrono` (3 times, for pretty printing only).

I guess we could also not use Abseil and not install, but that is a silly option.

**Comment by coryan** [comment]
Vote for option 1: use Abseil and do not provide install targets here.

**Comment by coryan** [comment]
Vote for option 2: use Abseil and punt on how it gets installed here.

**Comment by coryan** [comment]
Vote for option 3: use Abseil and provide hacky install targets for it here.

**Comment by coryan** [comment]
Vote for option 4: do not use Abseil here.

**Comment by garye** [comment]
Can you point to background on why these are the only options? I think I'm aware of the issues in general but a reference here would be good...

**Comment by coryan** [comment]
Good point, updated above.

**Comment by garye** [comment]
I think it's just a matter of time before our major dependencies use abseil. Look around gRPC core or protobuf (https://github.com/google/protobuf/issues/3688). 

Voting for #1 although I don't have a strong opinion on install targets one way or the other.

**Comment by sduskis** [comment]
@garye and I spoke yesterday.  We would like to use our C++ client as a basis for PHP, C#, Ruby, Node.js and Python.  As such, we would like to be able to provide a simpler install target for those languages, which means Abseil is not going to work well.

For now, we'll remove Abseil, and the few methods that expose Abseil classes will have to use alternative constructs.  Once grpc and protobuf use Abseil, our library will move to Abseil as well.

**Comment by coryan** [comment]
Ack.  Closing this bug, will open specific bugs to remote each Abseil component we are using.
