### ISSUE TITLE
Run performance tests daily

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/google-cloud-cpp#239]
There should be 4 tests that are run daily:

- latency 
- throughput
- scan test 
- endurance test.  

I'll add more details on this bug.

**Comment by sduskis** [comment]
Here's the code: https://github.com/GoogleCloudPlatform/google-cloud-cpp/tree/master/bigtable/benchmarks

**Comment by coryan** [comment]
@sduskis Do we need to do anything additional beyond the Jenkins builds already running?  If not, then we can close this.  I am sure there are things to improve, but I would rather open specific github issues for them.
