### ISSUE TITLE
Create an example and CI build to test the 'install' target

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#24]
At the end of this task we will have:

* A test for the install target: this is a program that uses the Cloud Bigtable C++ client as installed by `make install`.
* A CI build that exercises this test.

This is because it is too easy to forget header files, or libraries in the `install` rules and then the library is unusable.

**Comment by coryan** [comment]
See my comments in the last commit:

* We are including absl/*.h headers from our headers. That would
  force users to have the absl headers around.  But the headers
  for abseil are not installed by abseil.

* We are using the absl libraries, which are not designed, nor do
  they support, to be installed.

But how will a user link against our libraries?  At this point they can only
use them as a submodule.
]

**Comment by mbrukman** [comment]
@coryan wrote:

> * We are including absl/*.h headers from our headers. That would
force users to have the absl headers around. But the headers
for abseil are not installed by abseil.
>
> * We are using the absl libraries, which are not designed, nor do
they support, to be installed.

Maybe this should be filed as a bug / feature request for Abseil?

Surely they would like their library to be used by developers through the standard methods of including headers and linking against shared libraries; I don't think it's reasonable that every project that uses Abseil should be including it as a submodule — what if some projects use Mercurial and some use Git? What if the project wants to #include Abseil headers directly, and not transitively via a project such as this one?

**Comment by coryan** [comment]
> Maybe this should be filed as a bug / feature request for Abseil?

There is one, with active discussion.

https://github.com/abseil/abseil-cpp/issues/38
