### ISSUE TITLE
Test if disabling all caching accelerates docker builds

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#27]
Since all we do is download some packages before compiling gRPC and the client library it might be faster to download the packages every time instead of trying to cache the build results.  Test it out and report the results here, if faster, change the main build.

**Comment by mbrukman** [comment]
Fixed by PR #28.

**Comment by mbrukman** [comment]
@JustinBeckwith — if you want to assign it to the person who actually fixed this issue, that would be @coryan, since he is the author of PR #28; I just reviewed it and closed this bug. :-)
