### ISSUE TITLE
bigtable::SetCell should only accept millisecond timestamps.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#274]
The current API is confusing the signature is:

```C++
Mutation SetCell(std::string family, std::string column, std::int64_t timestamp,
                 std::string value);
```

However the timestamp value **must** be a multiple of 1,000.  That is error prone, we are giving users the impression that they can set the timestamp to values like `42`, when in fact they cannot.
We should make the API less error prone, and make it:

```C++
Mutation SetCell(std::string family, std::string column, std::chrono::milliseconds timestamp,
                 std::string value);
```

When the server supports microsecond timestamps we can add a new overload:

```C++
Mutation SetCell(std::string family, std::string column, std::chrono::microseconds timestamp,
                 std::string value);
```

**Comment by hemant-qlogic** [comment]
When the server supports microsecond timestamps we can add a new overload:

As per your above statement, do we have to add the new overloaded methods or replace the methods completed with the duration timestamp?
