### ISSUE TITLE
Complete unit tests for bigtable::Table::ReadModifyWrite()

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#304]
Add the tests missing in #303, including all `ReadModifyWriteRules` and multiple `ReadModifyWriteRules` in a single operation.

**Comment by hemant-qlogic** [comment]
Did not understand what is missing here. We have test cases for AppendValue(), IncrementAmount().
Do I need to add test case for using multiple IncrementAmount() in a test case as follows.
TEST(ReadModifyWriteRuleTest, MultipleIncrementAmount) {
  auto const proto =  bigtable::ReadModifyWriteRule::IncrementAmount("fam", "col", 52)
                                    .IncrementAmount("fam", "col", 10).as_proto();
  EXPECT_EQ(btproto::ReadModifyWriteRule::kIncrementAmount, proto.rule_case());
  EXPECT_EQ(62, proto.increment_amount());
  EXPECT_EQ("fam", proto.family_name());
  EXPECT_EQ("col", proto.column_qualifier());
}
This test case always fails as it returns the fresh ReadModifyWriteRule object.
Please suggest what is remaining in this.

**Comment by coryan** [comment]
Yes, testing with multiple values would be useful.  Also, you want the mock to return a proto Row with multiple cells and test that the output has what you expect.  That would have caught the problems fixed in #351 .
