### ISSUE TITLE
Implement Table::ReadRows() wrapper

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#32]
We need to write a brief design down for the ReadRows() and its associated wrappers.  We also need a breakdown of the tasks associated with this work as issues in this repository.

**Comment by DanielMahu** [comment]
The draft/wip DD is at go/cbt-cpp-readrows, with a list of proposed subtasks at the end.

**Comment by coryan** [comment]
Changed the name to reflect what we are actually doing in this issue.

**Comment by coryan** [comment]
Ping, can you give us an update?

**Comment by DanielMahu** [comment]
There is a draft of the code in https://github.com/DanielMahu/google-cloud-cpp/tree/row-reader

Still to do:

- [ ] proper unit tests
- [ ] rebase and integrate with RowSet
