### ISSUE TITLE
Decorate all public interfaces with the DLL import/export macros

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#328]
To be done after #99.  Once the magic header is created, we need to decorate each public function and header with the magic macros.  For example, this:

```C++
class Table { ... };
```

becomes

```C++
class GOOGLE_CBT_EXPORT Table { ... };
```

**Comment by coryan** [comment]
The actual spelling of the macro (`GOOGLE_CBT_EXPORT`) is TBD, it could be `GOOGLE_CLOUD_CPP_EXPORT` or `GCP_BIGTABLE_EXPORT`, or something.

**Comment by manish-qlogic** [comment]
@coryan ,

We were getting errors like
`alarm.obj : error LNK2001: unresolved external symbol "struct grpc_closure_scheduler * grpc_schedule_on_exec_ctx" (?grpc_schedule_on_exec_ctx@@3PAUgrpc_closure_scheduler@@A)
`
Any updates on ifgRPC support DLL creation on windows?

**Comment by coryan** [comment]
No news from the gRPC folks, let me ping them again.

**Comment by coryan** [comment]
For what is worth, the gRPC team does not plan to support DLLs on Windows, grpc/grpc#15333 for details.  I am going to unassign this project and remove it from the milestone.

@sduskis FYI.

**Comment by coryan** [comment]
We will not be pursuing this, there is not enough demand.  We can reopen the bug if the need arises.
