### ISSUE TITLE
Implement ClientConfig class

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#33]
Implement a class to configure the `bigtable::Table` client.  Write down what it does, separate the code to its own files, write tests, etc.

**Comment by paprat** [comment]
Shouldn't we close this one considering the fact that PR for this issue has been merged?

**Comment by mbrukman** [comment]
@paprat — see [my comment on the PR](https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/47#issuecomment-348485291): if that PR entirely addresses this issue then yes, go ahead and close this issue. In the future, you can also auto-close issues using the wording in the PR that GitHub understands.
