### ISSUE TITLE
Avoid copying in Table::ReadModifyWrite.

### ISSUE THREAD

**Issue by hemant-qlogic** [GoogleCloudPlatform/google-cloud-cpp#336]
The code below could cause the performance issue when a large number of ReadModifyWriteRules are applied to the table.

bigtable/client/table.h 
*request.add_rules() = rule.as_proto_move();
This need to be handle properly to remove the performance issue.

**Comment by coryan** [comment]
To rephrase that in more general terms: `Table::ReadModifyWrite()` has some data copying in the current implementation.  We do not expect this to be a big problem, but this is a nice optimization to do in the future.
