### ISSUE TITLE
Unit test for  MetadataUpdatePolicy with EmbeddedServer

### ISSUE THREAD

**Issue by manish-qlogic** [GoogleCloudPlatform/google-cloud-cpp#347]
Wrie unit tests for MetadataUpdatePolicy with EmbeddedServer, currently bigtable/benchmarks/ uses EmbeddedServer to verify requests. It can be further enhanced to verify if requests include the right metadata.

**Comment by manish-qlogic** [comment]
please see #190 for more details

**Comment by sduskis** [comment]
Is there more to do here?

**Comment by coryan** [comment]
Yes.  The unit test has been proposed in #367, but it crashes.  I am helping @manish-qlogic track down the  crash.  I think I may have found the answer:

https://github.com/coryan/google-cloud-cpp/commit/1b700a263587de228e7c14a6d8798790b978cdd6
