### ISSUE TITLE
Optimize error reporting via bigtable::internal::RpcUtils<>

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#358]
Many of the APIs are implemented like this (pseudo-code, with `Table::Apply` as example):

```C++
std::string error_message = "Table::Apply(" + table_name() + ")";
RpcUtils::Blah(..., error_message.c_str());
```

the problem is that this allocates a string to report error messages, but the string goes unused in most calls as there are no errors.  We did this because there was no other way to provide an indication to the user about what table or instance had the problem otherwise.  With the introduction of the `MetadataUpdatePolicy` we can do better.  We can say:

```C++
RpcUtils::Blah(... metadata_update_policy, ..., "Table::Apply" /* received as char const* */);
```

The `metadata_update_policy` object has the name of the target table (or instance, or project) embedded in it.  We can create a meaningful error message without having to allocate a string in each call.

**Comment by coryan** [comment]
@roopak-qlogic I just noticed that this bug was assigned to you.  Sorry, but I finished the implementation this afternoon.  Take a look and if it looks good to you we can merge my version, but if you have a better one we will use your version.

**Comment by roopak-qlogic** [comment]
yesterday, I just started to understand issue and code.
No Implementation started, so your version is good to go.
