### ISSUE TITLE
Implement TableAdmin::CreateTableFromSnapshot.

### ISSUE THREAD

**Issue by paprat** [GoogleCloudPlatform/google-cloud-cpp#375]
Implement TableAdmin::CreateTableFromSnapshot that returns std::future<>. #329

**Comment by roopak-qlogic** [comment]
Just trying to understand,signature of  CreateTableFromSnapshot, for noex implementation it should be like  ?
::google::bigtable::admin::v2::Table CreateTableFromSnapshot( bigtable::SnapshotId const& snapshot_id, std::string table_id, grpc::Status& status)

**Comment by paprat** [comment]
We need to return ::google::bigtable::admin::v2::Table wrapped in std::future. You can refer to [this](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/ed6f7f82c5bb20a80b98c3e873b50d3ee95ad0be/google/cloud/bigtable/instance_admin.cc#L47).
