### ISSUE TITLE
Implement TableAdmin::SnapshotTable.

### ISSUE THREAD

**Issue by paprat** [GoogleCloudPlatform/google-cloud-cpp#380]
Implement SnapshotTable to take functor as argument and returns void. #329

**Comment by manish-qlogic** [comment]
@coryan 

Issues #379 and #380 are both for implementing TableAdmin::SnapshotTable.

is #380 similar to #632  and depends on implementation of async apis?

**Comment by coryan** [comment]
@manish-qlogic yes, we should post-pone #380 until after the other async changes.

**Comment by sduskis** [comment]
@coryan, can we close this?

**Comment by coryan** [comment]
I think so.
