### ISSUE TITLE
Implement InstanceAdmin::GetInstance

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#419]
This issue includes:

- [x] Implementing the integration test.
- [x] Implementing the sample snippet.
- [x] Implementing the unit tests for "no errors", "unrecoverable error", "retry with recoverable errors".
- [x] Implementing the function itself.

**Comment by roopak-qlogic** [comment]
I have done the Implementation, Need to complete test cases,  assuming GetInstance signature as:
:google::bigtable::admin::v2::Instance GetInstance(grpc::Status& status);
So I would like to confirm, Is my understanding correct?

**Comment by coryan** [comment]
First, it is better if you make this in several smaller PRs than a large one.  One PR with the implementation and the unit tests is a good start.  The signatures should be:

```C++
google::bigtable::admin::v2::Instance bigtable::noex::InstanceAdmin::GetInstance(
  std::string const& instance_id, grpc::Status& status);

google::bigtable::admin::v2::Instance bigtable::InstanceAdmin::GetInstance(
  std::string const& instance_id);

```

Note the difference for the one in the `noex` namespace.  I would prioritize the implementation in `bigtable::InstanceAdmin` over the one in the `noex` namespace.

**Comment by roopak-qlogic** [comment]
Thanks, I will do that

**Comment by coryan** [comment]
All steps are done.  Closing.
