### ISSUE TITLE
Implement InstanceAdmin::DeleteInstance

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#420]
This issue includes:

- Implementing the integration test.
- Implementing the sample snippet.
- Implementing the unit tests for "no errors", "unrecoverable error", and "no retry with recoverable errors" (because it is non-idempotent).
- Implementing the function itself.

**Comment by coryan** [comment]
> @coryan
> Would this be a normal sync method?

@manish-qlogic: Yes.

**Comment by manish-qlogic** [comment]
@coryan 
integration test has a dependency on CreateInsance, so we first need to close CreateInstance PR.
I am assuming following steps for integration tests of DeleteInstance
1. ListInstance and expect instance doesn't exists.
2. CreateInstance 
3. ListInstance and expect instance exists.
4. DeleteInstance and expect instance doesn't exists.

**Comment by coryan** [comment]
Yes. We can start with an incomplete implementation of `CreateInstance`, something that is good enough for the other tests to be completed while we improve/complete `CreateInstance`.  We also would want to have a version of `DeleteInstance` working so we can cleanup after ourselves in the tests, so either way we need partial versions to make progress.  Let me know what changes to make in #457 so I can commit that and unblock you.

Your list of tests is fairly complete.
