### ISSUE TITLE
Implement InstanceAdmin::UpdateInstance

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#421]
At the end of this task we will have an implementation of `InstanceAdmin::UpdateInstance()`:

- We should use `InstanceAdmin::PartialUpdateInstance()` under the hood.
- This task includes creating the integration tests.
- This task includes creating the sample snippet.
- The function should take an instance description as a parameter (follow existing patterns to wrap protos)
- One overload should return `std::future<>` which is satisfied when the operation completes.
- One overload takes a Functor that is called when the operation completes.
- The function should implement unit tests:
  - the unit tests for "no errors"
  - the unit tests for an error trying to start the long running operation.  Because this is a non-idempotent operation all errors in this phase are unrecoverable.
  - the unit tests for "an error trying to determine if the operation completed", because those are idempotent operations we should retry them.

The operation should take (maybe via policies) arguments to determine how often and for how long to poll the long running operation.

**Comment by manish-qlogic** [comment]
@coryan ,
In the `BigtableInstanceAdmin`, `UpdateInstance` method is for a blocking call and `AsyncUpdateInstance` method is for a non blocking call.
With this open issue, we will only implement the blocking or unary method `UpdateInstance`. This is similar to CreateInstance implementation.

So the questions are,
1. Is above understanding correct?
2. Do we have plan to implement AsyncUpdateInstance in the future?

**Comment by manish-qlogic** [comment]
@coryan ,
I think this issue is fixed, any specific reason to keep it open?

**Comment by coryan** [comment]
I believe we have not integrated this change with the polling policies, righ?

**Comment by manish-qlogic** [comment]
yes, we have not integrated the changes for polling policies, but created #578 to track that.

**Comment by coryan** [comment]
Ack.  Closing then.
