### ISSUE TITLE
Implement InstanceAdmin::CreateCluster

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#422]
At the end of this task we will have an implementation of `InstanceAdmin::CreateCluster()`:

- This task includes creating the integration tests.
- This task includes creating the sample snippet.
- The function should take an instance description as a parameter (follow existing patterns to wrap protos)
- One overload should return `std::future<>` which is satisfied when the operation completes.
- One overload takes a Functor that is called when the operation completes.
- The function should implement unit tests:
  - the unit tests for "no errors"
  - the unit tests for an error trying to start the long running operation.  Because this is a non-idempotent operation all errors in this phase are unrecoverable.
  - the unit tests for "an error trying to determine if the operation completed", because those are idempotent operations we should retry them.

The operation should take (maybe via policies) arguments to determine how often and for how long to poll the long running operation.

**Comment by manish-qlogic** [comment]
@coryan 
do we have a work in progress branch for InstanceAdmin::CreateInstance?
i think rework can be reduced if we have a starting point.

**Comment by coryan** [comment]
I expect `CreateCluster` and `CreateInstance` to be similar, yes.

**Comment by roopak-qlogic** [comment]
Also As per issue description will function take an instance description as a parameter ?

**Comment by coryan** [comment]
You will need to fill up one of these protos:

https://github.com/googleapis/googleapis/blob/master/google/bigtable/admin/v2/bigtable_instance_admin.proto#L257

I think `bigtable::ClusterConfig` has most of the information you need, you also need the instance id and cluster id, those should be separate parameters (and please consider using strong types for them).

**Comment by coryan** [comment]
#600 is a PR still open to implement the integration tests and sample code.  The PR failed to complete the tests in the last pass.

**Comment by roopak-qlogic** [comment]
I did not get chance to do that, I will Fix and pushed for review
