### ISSUE TITLE
Implement InstanceAdmin::UpdateCluster

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#424]
At the end of this task we will have an implementation of `InstanceAdmin::UpdateCluster()`:

- This task includes creating the integration tests.
- This task includes creating the sample snippet.
- The function should take an instance description as a parameter (follow existing patterns to wrap protos)
- One overload should return `std::future<>` which is satisfied when the operation completes.
- One overload takes a Functor that is called when the operation completes.
- The function should implement unit tests:
  - the unit tests for "no errors"
  - the unit tests for an error trying to start the long running operation.  Because this is a non-idempotent operation all errors in this phase are unrecoverable.
  - the unit tests for "an error trying to determine if the operation completed", because those are idempotent operations we should retry them.

The operation should take (maybe via policies) arguments to determine how often and for how long to poll the long running operation.

**Comment by manish-qlogic** [comment]
@Coroyan,
I think, we will expose  `Cluster` directly to the user. There is no need to writer config wrapper. Please suggest?

**Comment by coryan** [comment]
There is already a `ClusterConfig` wrapper.  Any reason it cannot be used?

**Comment by coryan** [comment]
As far as I can tell this was fixed by #596.  Closing.
