### ISSUE TITLE
Implement InstanceAdmin::DeleteCluster

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#425]
This issue includes:

- [ ] Implementing the integration test.
- [x] Implementing the sample snippet.
- [x] Implementing the unit tests for "no errors", "unrecoverable error", and "no retry with recoverable errors" (because it is non-idempotent).
- [x] Implementing the function itself.

**Comment by manish-qlogic** [comment]
@coryan
Please confirm following  
1. I am assuming it to be sync call.
2. is there any difference between value of x-goog-request-params for DeleteInstance and DeleteCluster?

**Comment by coryan** [comment]
> I am assuming it to be sync call.

Yes.

> is there any difference between value of x-goog-request-params for DeleteInstance and
> DeleteCluster?

I believe so, the full cluster name needs to be passed in `x-goog-request-params`, as in `projects/.../instances/.../clusters/...`.  I typically look at this file:

https://github.com/googleapis/googleapis/blob/master/google/bigtable/admin/v2/bigtableadmin_gapic.yaml

to figure this out.

**Comment by coryan** [comment]
Good question. @sduskis I think your are the authority here.  Is that a bug in the gapic file?  Or should we retry DeleteCluster on temporary failures?

**Comment by coryan** [comment]
@manish-qlogic feel free to send a PR assuming it is a non-idempotent call, if we change our minds about this the code changes will be small.  FYI: @sduskis.

**Comment by manish-qlogic** [comment]
@coryan  
another question on creation of MetadataUpdatePolicy.

I can think of 2 approaches

**Approach 1 : MetadataUpdatePolicy is responsible for constructing resource name.**
This approach will use StrongType and pass IDs to MetadataUpdatePolicy, the responsibility to construct appropriate resource name lies with MetadataUpdatePolicy. This leads to few more constructors in MetadataUpdatePolicy. This approach is currently used.

**Approach 2 : Respective Caller is responsible for constructing resource name.** 
this appraoch will use following constructor
```
  MetadataUpdatePolicy(std::string const& resource_name,
                       MetadataParamTypes const& metadata_param_type);
```
and caller will construct the resource name and pass it to the MetadataUpdatePloicy.

Please suggest.

**Comment by coryan** [comment]
I think I like approach 2 better, thanks for checking.

**Comment by manish-qlogic** [comment]
@coryan ,
I think this issue is fixed, any specific reason to keep it open?

**Comment by coryan** [comment]
I cannot see an integration test for this function, did I miss it?

**Comment by manish-qlogic** [comment]
we do not have integration test, but #503 was created to track it.

**Comment by coryan** [comment]
Ack. Closing then.
