### ISSUE TITLE
Wrap TableAdmin::CheckConsistency in a loop.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#426]
The response from the `TableAdmin::CheckConsistency` rpc might be `false` simply because replication has not caught up *yet*.  We want the client library to retry the operation multiple times if needed, until the response is successful or some limited number of retries have taken place.

At the end of this task we should have:

- [ ] A new version of the C++ `TableAdmin::CheckConsistency` function that returns a `std::future<>` as parameter.  The future is satisfied when (a) the server responds `true` to a `CheckConsistency` request or (b) all the retries as exhausted and all returned false.  The future is satisfied with an exception if all the retries fail with exceptions.
- [ ] A new version of the C++ `TableAdmin::CheckConsistency` function that takes a Functor, the functor receives a satisfied `std::future<>` as input, with the same semantics as above.
- [ ] Unit tests for "success", "failure", *and* exceptional conditions.
- [ ] An integration test for the function.
- [ ] A sample snippet for the function.

**Comment by hemant-qlogic** [comment]
Writing down my understanding after suggestions from Carlos.
1. New function WaitForConsistencyCheck will be added in TableAdmin.cc
    a. Function Parameter 1: A function which implements the ConsistencyCheck Task.
    b. Function Parameter 2: A callback Functor is passed with this function.
    c. Function Parameter 3: A new PollingPolicy used for the async call will be passed.
    d. Function Parameter 4: Table ID.
    e. Function Parameter 5: ConsistencyToken

    f. std::async call to the consistency check task will be added.
    g. Return value satisfied std::future<bool> of std::async call is passed to the callback Functor.
    h. Function returns void.

2. New function WaitForConsistencyCheckImpl will be added which implements ConsistencyCheck task. 
    a. Creates new request "CheckConsistencyRequest" and make a call to it.
    b. If response is exception, then throw exception.
    c. If response is true then return to the calling function.
    d. Sleep as per polling policy.
    e. Loop this logic till the polling policy count is exhausted.

3. New class PollingPolicy need to be added with following functionalities.
    a. Private members:
       int max_polling_count ;
       int polling_timeout ;
       int polling_index ;

     b. public members:
       int PollingCount() ;
       std::duration timeout();
       bool Exhausted();
   
This is what I can think for implementing async implementation of TableAdmin.
