### ISSUE TITLE
Create "Core Reading and Writing" Tutorial

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#453]
At the end of this task we will have a tutorial page describing the basic reading and writing from Bigtable APIs.  The page will be linked from the top-level Bigtable documentation here:

https://googlecloudplatform.github.io/google-cloud-cpp/latest/bigtable/index.html

It is enough to create a document in `bigtable/doc`, like the existing `bigtable-hello-world.dox`.

The tutorial should cover (each one of these tasks should become its own GitHub issue):

- [ ] Create a data client.
- [ ] Create a data client with an explicit number of connections in the connection pool (e.g. use 2 times the number of CPUs).
- [ ] Create a table object (assuming the table exists).
- [ ] Read one row.
- [ ] Read an open range of rows.
- [ ] Read a closed range of rows.
- [ ] Read a row but only get the latest cell.
- [ ] Read a range of rows (open or closed, does not matter) but only get the latest cell.
- [ ] Read a range of rows (open or closed, does not matter) but only get the row keys (use the `bigtable::Filter::StripValueTransformer`).
- [ ] Call MutateRow() with a single cell, using an explicit timestamp.
- [ ] Call MutateRow() and use the C++ clock to populate the row with "current time".
- [ ] Call DeleteRow() to delete one row.
- [ ] Use MutateRows() to write 10 rows in one request.

**Comment by sduskis** [comment]
This is subsumed by #615
