### ISSUE TITLE
Create a "Table Admin" Tutorial

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#455]
At the end of this task we will have a tutorial page describing the basic reading and writing from Bigtable APIs. The page will be linked from the top-level Bigtable documentation here:

https://googlecloudplatform.github.io/google-cloud-cpp/latest/bigtable/index.html

It is enough to create a document in bigtable/doc, like the existing bigtable-hello-world.dox.

The tutorial should cover (each one of these tasks should become its own GitHub issue):

- [ ] How to create a TableAdmin object.
- [ ] Create a table with column families.
- [ ] List all the tables with ListTables.
- [ ] Get the details of a table with GetTable.
- [ ] Delete a table with DeleteTable.
- [ ] Use GetTable and CreateTable to create a table if it does not exist.
- [ ] Use GetTable to modify the column families.
- [ ] Show how to use both GC policies.
- [ ] Show how to use a combined GC policy.

**Comment by sduskis** [comment]
This is subsumed by #615
