### ISSUE TITLE
Create a "Instance Admin" Tutorial.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#456]
At the end of this task we will have a tutorial page describing the basic reading and writing from Bigtable APIs. The page will be linked from the top-level Bigtable documentation here:

https://googlecloudplatform.github.io/google-cloud-cpp/latest/bigtable/index.html

It is enough to create a document in bigtable/doc, like the existing bigtable-hello-world.dox.

The tutorial should cover (each one of these tasks should become its own GitHub issue):

- [ ] Create an InstanceAdmin object.
- [ ] Create a development instance with HDD.
- [ ] Create a production instance with SSD.
- [ ] Get the details of an instance.
- [ ] Use GetInstance + CreateInstance() to create an instance if it does not exist.
- [ ] ListInstance to list all the instances.
- [ ] UpdateInstance: change something (maybe number of nodes)?
- [ ] Delete an instance: with a lot of warnings!!
- [ ] Create a new cluster.
- [ ] Get the details of a cluster.
- [ ] List all the clusters.
- [ ] Update a cluster
- [ ] Delete a cluster.
- [ ] Show how to use more than one cluster per instance.

**Comment by sduskis** [comment]
This is subsumed by #615
