### ISSUE TITLE
File bug and/or submit patch for vcpkg

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#46]
Microsoft has a [project](https://github.com/Microsoft/vcpkg) to support open source packages under MSVC, much like the FreeBSD ports collection.  They have patches / scripts to compile protobuf, grpc, abseil, etc.  We should submit a bug and/or patches to compile the client library.

**Comment by ras0219-msft** [comment]
@coryan we'd love to chat about your experience with vcpkg so far! Send us a mail at vcpkg@microsoft.com if you're interested :)

**Comment by coryan** [comment]
For the record, I need to get internal approval before I can sign the CLA and submit patches to `vcpkg`.  I will be submitting some PRs to `google-cloud-cpp` to make the vcpkg patches as small as possible.

**Comment by ras0219-msft** [comment]
Of course! I'd still love to chat regardless of any upstream submissions.

**Comment by coryan** [comment]
To keep the other Google devs updated, I filed Microsoft/vcpkg#3093 to start the discussion with the vcpkg folks.

@ras0219-msft my experience using vcpkg so far has been excellent.  It has made packaging Open Source libraries for Windows very enjoyable.

**Comment by coryan** [comment]
The PR has been merged, there are some suggestions to improve our packaging that I will follow up on shortly.
