### ISSUE TITLE
Troubleshoot problem in the unit test in table_admin_test

### ISSUE THREAD

**Issue by hemant-qlogic** [GoogleCloudPlatform/google-cloud-cpp#470]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Is this an issue affective the `google-cloud-cpp` project?

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?

Remove the ones that do not apply.

- Cloud Bigtable.

### What version of `google-cloud-cpp` are you using?

Please include the output from `git rev-parse HEAD` if you are compiling from
source, or the version number from correct `*/version.h` file.

### What compiler and version are you using?

Please include the output of `g++ -v` or the equivalent command-line flag.

### What operating system and version are you using?

If you are using a Linux distribution include the name and version of the
distribution too.

### What were you trying to do?

If possible, produce a recipe for reproducing the problem.

### What did you expect to see?

What was the behavior you expected from the library?

### What did you see instead?

What was the behavior you actually observed?

### Anything else

**Comment by hemant-qlogic** [comment]
Here is the link where table_admin_test received no response for 10m0s.
https://travis-ci.org/GoogleCloudPlatform/google-cloud-cpp/jobs/372332188

similar to the issue #441

**Comment by coryan** [comment]
I doubt this is the same as #441.  I think what is happening here is that the call to `future.get()` here:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/461/files#diff-6d98ccddf864383a583e597e019f3b4fR748

never returns, because `EXPECT_DEATH_IF_SUPPORTED()` uses a separate process, which will never get the future satisfied.  I believe this test should be completely disabled if exceptions are not enabled.

**Comment by coryan** [comment]
@hemant-qlogic Is this still a problem?  If not, please close.

**Comment by hemant-qlogic** [comment]
The problem was solved and test case is working now.
