### ISSUE TITLE
Document length limits for instance id, display name, cluster id, etc.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#480]
Very long display names are rejected by the Cloud Bigtable server, but I could not immediately find documentation describing how long they can be.  Maybe I am just blind but the [proto files](https://github.com/googleapis/googleapis/blob/master/google/bigtable/admin/v2/instance.proto) do not seem to describe these limitations.

@mbrukman @ghaisa @sduskis any thoughts on where I can find a description of these limits?

**Comment by mbrukman** [comment]
@garye, do you have pointers on hard limits for strings such as IDs, names, etc.?

**Comment by garye** [comment]
MinDisplayNameLength = 4;
MaxDisplayNameLength = 30;
MaxDescriptionLength = 140;

**Comment by garye** [comment]
Reached out offline with others.

**Comment by coryan** [comment]
Documented in our code.
