### ISSUE TITLE
Implement/complete Integration Test for InstanceAdmin::ListCluster

### ISSUE THREAD

**Issue by hemant-qlogic** [GoogleCloudPlatform/google-cloud-cpp#482]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Is this an issue affective the `google-cloud-cpp` project?

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?

Remove the ones that do not apply.

- Cloud Bigtable.

### What version of `google-cloud-cpp` are you using?

Please include the output from `git rev-parse HEAD` if you are compiling from
source, or the version number from correct `*/version.h` file.

### What compiler and version are you using?

Please include the output of `g++ -v` or the equivalent command-line flag.

### What operating system and version are you using?

If you are using a Linux distribution include the name and version of the
distribution too.

### What were you trying to do?

If possible, produce a recipe for reproducing the problem.

### What did you expect to see?

What was the behavior you expected from the library?

### What did you see instead?

What was the behavior you actually observed?

### Anything else

**Comment by hemant-qlogic** [comment]
When List cluster was implemented there was not  CreateCluster, ListInstances were implemented, so integration test were not able to complete.
Now complete the integration test for CreateCluster and also complete the example.

**Comment by hemant-qlogic** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/fb46a358cd290b17bb812a0acb0f8041f7785e19/bigtable/tests/instance_admin_integration_test.cc#L158
Integration test is already added in the earlier PR. Now waiting for Issue#422: Implement InstanceAdmin::CreateCluster to complete the test case.

**Comment by hemant-qlogic** [comment]
Integration Test cases are not working with emulator. It always fails.
How to successfully run these test cases with emulator.

**Comment by coryan** [comment]
That might be because the (instance admin) emulator is not fully implemented and we need to implement the missing pieces as we go along.  You need to replace the code here:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/fb46a358cd290b17bb812a0acb0f8041f7785e19/bigtable/tests/instance_admin_emulator.cc#L119

with a function that iterates over the instances and returns only the relevant clusters.
