### ISSUE TITLE
Consider using ExternalProject_Add for dependencies.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#518]
google-cloud-cpp with CMake supports dependencies in multiple ways:

- As git submodules.
- As pre-installed libraries found via find_package()
- As pre-installed libraries found via pkg-config.
- As pre-installed libraries found via vcpkg.

This bug proposes an alternative for submodules, the other schemes would be left untouched.

With Bazel we generally use external projects, where the build system downloads an specific version (often as a tarball) of the code and compiles that version.  CMake supports a similar scheme, via the `ExternalProject` module [[1]](https://cmake.org/cmake/help/v3.5/module/ExternalProject.html).  External projects have some advantages:

- Generally they download smaller amounts of code, so the CI builds would be faster.
- The CMakes are not included into the main project so our namespace for targets is not polluted by the dependencies: e.g. if a submodule adds a `bigtable_test` target that will not affect our CMake files.
- It should be easier to keep the versions used for Bazel and CMake in sync if we use the same scheme to download them.

External projects have some disadvantages:

- Slightly harder to add new dependencies (is that an advantage maybe?) because the targets have to be explicitly defined.
- As dependencies add sub-dependencies we need to manually update our list of dependencies too.  That might be an advantage too because Bazel requires the same thing.

**Comment by coryan** [comment]
For the record, with external projects one has to manually define the targets (libraries and binaries) as "imported" targets.  The reasons are somewhat non-obvious:

- The definition of targets happens at CMake configuration time, that is, when CMake runs.
- Downloading, compiling, and staging external projects happens at build time, after the configuration is created.

When CMake is running and generating the list of targets and their dependencies none of the `*.cmake` nor `*.pc` files that the external project might create are built yet, so it is impossible to use `find_package()` to automatically configure the targets.

Therefore, one has to "predict" where the external project will stage libraries, what their names would be, and what their dependencies are.  This is not *that* hard, because the external project is under our control, we decide what version, we decide what configuration parameters are given to the build, etc.

**Comment by ras0219-msft** [comment]
If vcpkg had an "embedded" mode that would enable an experience like git submodules / ExternalProject (all dependencies would be downloaded and built transparently as part of configure), would you prefer that? In this proposed mode, the user would not need to get vcpkg themselves.

**Comment by coryan** [comment]
I think #1248 better captures all the changes we need to make. Closing for now.
