### ISSUE TITLE
Implement ListClusters in instance admin emulator 

### ISSUE THREAD

**Issue by hemant-qlogic** [GoogleCloudPlatform/google-cloud-cpp#528]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?

Remove the ones that do not apply.

- Cloud Bigtable.
- Cloud Firestore.

### What version of `google-cloud-cpp` are you using?

Please include the output from `git rev-parse HEAD` if you are compiling from
source, or the version number from correct `*/version.h` file.

### What compiler and version are you using?

Please include the output of `g++ -v` or the equivalent command-line flag.

### What operating system and version are you using?

If you are using a Linux distribution include the name and version of the
distribution too.

### What were you trying to do?

If possible, produce a recipe for reproducing the problem.

### What did you expect to see?

What was the behavior you expected from the library?

### What did you see instead?

What was the behavior you actually observed?

**Comment by hemant-qlogic** [comment]
we need to implement the ListClusters function in the instance admin emulator and then we need to call these new examples for run_examples_utils.sh

**Comment by sduskis** [comment]
@hemant-qlogic: If there's nothing else to do for this bug, please close it.  Otherwise, please describe what else needs to be done.

**Comment by hemant-qlogic** [comment]
After ListCluster successful integration test I need to test the examples/bigtable_samples_instance_admin test cases. After successful testing of these cases I can close this task. Still there is incomplete implementation of createinstance #610 on which task #587 depends. example contains ListCluster sample code when all these successful then I will close this task.

**Comment by hemant-qlogic** [comment]
ListClusters Examples are depends on the ListCluster implementation so added these in #587.
So this can be closed now.
