### ISSUE TITLE
Use local instance of httpbin for storage::internal::CurlRequest integration tests.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#542]
The integration tests in `storage/tests/curl_request_integration_tests.cc` connect to a remote server.  We want to run the integration tests locally to make the tests more hermetic.

**Comment by coryan** [comment]
Consider using `gunicorn` and `httpbin` like so:

```sh
pip install gunicorn
pip install httpbin
gunicorn httpbin:app
```

We would need to install these on the Docker images for all builds.

**Comment by mbrukman** [comment]
Wouldn't it be easier and faster to just run:

```bash
python -m SimpleHTTPServer 8000
```

to address 2 of the 4 use cases? And to address the other 2, a simple Python file can be written that converts URL params into returned headers to simulate what is being done with the external server. If you're going to go so far as to install all those tools, might as well just install Python and have a simple Python server that you control directly that you can implement all the behaviors in.

I would be open to writing such a Python web server script if that's what you elect to do.

**Comment by coryan** [comment]
If you can write the script that would be awesome.

When I looked into this I gathered that `SimpleHTTPServer` can only handle `HEAD` and `GET` verbs.  Eventually we need to handle all the verbs that the JSON API uses (`HEAD`, `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` at least).  If I got that right, `SimpleHTTPServer` might not be the best choice.

**Comment by mbrukman** [comment]
I'm sure you're right about SimpleHTTPServer, but without instantiating a custom server whose implementation and endpoints you entirely control, how can you write complete integration tests? What remote server will help you test all the other verbs, particularly with custom error codes for some responses but not others?

**Comment by coryan** [comment]
> but without instantiating a custom server whose implementation and endpoints you entirely control,
> how can you write complete integration tests?

You can't, but I am not sure you need to.

> What remote server will help you test all the other verbs, particularly with custom error codes
> for some responses but not others?

`httpbin` handles the other verbs.  No, it does not handle produce custom error codes for some responses and not for other, but it does produce custom error codes for specific requests.

The testing strategy is:

- Test `CurlRequest` against `httpbin` (currently remote, ideally local) to make sure it can produce all the kinds of requests we need.
- Test `CurlRequest` against `httpbin` (currently remote, ideally local) to make sure it can parse and report all the possible responses.  Note that we might use a subset of the request types to generate all the response types.
- Mock `CurlRequest` to test that the higher level components make the right calls to it, and correctly handle all expected responses from `CurlRequest`.
- Run integration tests against production for the higher level components, including common failures (such as "object not found").

If you want to argue that we are using knowledge about how `CurlRequest` is implemented in this testing strategy then the answer is: yes, we are, less than ideal but not terrible.

Happy to discuss in more detail if you think this misses some tests.  @houglum FYI.

**Comment by mbrukman** [comment]
@coryan – agree that it's not ideal and not terrible at the same time. Sounds like `httpbin` might address all of these use cases for you, so you might not need the custom Python webserver I proposed, which is fine. Let me know if it will be needed and if it becomes a blocker for you in the future.
