### ISSUE TITLE
Add arguments to all upload APIs that set checksums.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#564]
When uploading: the application should be able to provide the checksum value for the objects, in which case the library will not compute them but pass them on to the server.  The application should also be able to ask the library to compute the checksum values on its behalf, in which case the library will pass on the computed values to GCS.

**Comment by coryan** [comment]
@houglum does this make sense?  If not, please provide a better description.

**Comment by houglum** [comment]
Yeah, it's worth considering whether or not we want to add this functionality.  

Pros:

*  Convenience. Our service relies on MD5 and CRC32C checksums for integrity checking, so it makes sense that we might provide utility methods to calculate those for local files.

Cons:
*  Bloat / scope creep. It's arguable as to whether our client library should be responsible for computing those checksums, as opposed to allowing users to do so themselves -- there are plenty of utilities out there to calculate them, allowing users to then pass the computed checksum to one of our methods (or calculate checksums for downloaded objects).

I think it's worth checking out our other storage client libraries and seeing what they do, at least for the download case (comparing the downloaded bytes' checksum to the checksum in the X-Goog-Hash header of the response).

**Comment by coryan** [comment]
This was fixed in #1344.
