### ISSUE TITLE
Define common scenarios for Google Cloud Storage

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#577]
We need to list the common scenarios for Google Cloud Storage, get the list approved, and then write an example for each one.

Good news, there is an authoritative list here:

https://cloud.google.com/storage/docs/how-to

If I am reading this right we need:

### Working with Buckets

- [x] Creating Storage Buckets
- [x] Listing Buckets
- [x] Getting Bucket Information
- [x] Changing the Default Storage Class of a Bucket
- [ ] Moving and Renaming Buckets
- [x] Deleting Buckets

### Working with Objects

- [x] Uploading Objects
- [x] Listing Objects
- [x] Downloading Objects
- [x] Renaming, Copying, and Moving Objects
- [ ] Changing Storage Classes
- [x] Viewing and Editing Object Metadata
- [ ] Streaming Transfers
- [x] Deleting Objects

### Using Features

- [x] Using Bucket Labels
- [ ] Managing Object Lifecycles
- [x] Using Object Versioning
- [x] Using Requester Pays
- [x] Using Customer-Supplied Encryption Keys
- [x] Using Customer-Managed Encryption Keys

### Controlling Access

- [x] Making Data Public
- [x] Managing IAM Persmissions
- [x] Creating and Managing Access Control Lists
- [ ] Sharing and Collaboration
- [ ] Creating Signed URLs with gsutil (out of scope?)
- [ ] Creating Signed URLs with a Program
- [ ] Performing Authenticated Browser Downloads (out of scope?)

### Accessing Public Data

- [ ] Accessing Public Data

### Using with Other Products

All of these are probably out of scope:

- [ ] Interoperability (out of scope?)
- [ ] Migrating from Amazon S3 to Cloud Storage (out of scope?)
- [ ] Working with Big Data (out of scope?)
- [ ] Registering Object Changes
- [ ] Analyzing Access Logs (out of scope?)
- [ ] Configuring Cross-Origin Resource Sharing (CORS)

**Comment by coryan** [comment]
@frankyn I think this is now done based on what we did for the Alpha checklist?  And if not, I think we should create smaller bugs for it.  Feel free to create new bugs if we need them.

**Comment by frankyn** [comment]
One follow-up might be `Streaming Transfers`, but I think that's for Beta?
