### ISSUE TITLE
Simplify integration tests for admin CRUD operations

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#593]
We currently have one test per operation but the create/list/delete tests all look the same:

- Pick a random object (table, instance, cluster) to create.
- List existing objects, make sure the object is not in the list
- Create the object
- List existing objecst, make sure it is there.
- Delete the object
- List existing objects, make sure the object is no longer there.

Sometimes we "get" the object after creating it, or maybe we "update" the object after creating it.
Instead of having one integration test per API we should have a single `CreateListDelete` test.

**Comment by coryan** [comment]
Sorry, I messed with the milestone when I should not have.

**Comment by paprat** [comment]
Shouldn't we merge update with create/list/delete tests?

**Comment by coryan** [comment]
> Shouldn't we merge update with create/list/delete tests?

Yes. I think a simpler CRUD test would look like this:


- Pick a random name for the entity
- Create any prerequisites (e.g. the instance to contain the clusters)
- List
- Create
- List to verify it was created
- Get
- Update
- Get to verify it was updated
- Delete
- List to verify it is no longer there
- Delete prerequisites.

That is one test that checks all operations.

**Comment by coryan** [comment]
> Is it for instance admin or Table admin ?

Both I think.
