### ISSUE TITLE
Do not run the macOS build for every PR; just run on master

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#60]
The macOS build rarely finds any problems, and it is unlikely to be an important platform for the target libraries.   Certainly some of our users and developers will take advantage of it, but it is unlikely to be the main platform.

It is often very delayed in Travis CI though, if we run it on a nightly build we will get most of the benefits, and save ourselves a lot of waiting.

**Comment by mbrukman** [comment]
Alternatively, we can just disable running the macOS build for each PR, and just run it on `master` so it's async, but will catch issues better than a nightly, which will include a bunch of changes from the day. 

Also, running daily builds on a weekend if there are no changes is also wasting Travis CI's limited macOS build cycles.

**Comment by coryan** [comment]
I like that idea, let me change the PR and send it to you again.
