### ISSUE TITLE
Improve cluster handling for CreateInstance and DeleteInstance in InstanceAdminEmulator 

### ISSUE THREAD

**Issue by manish-qlogic** [GoogleCloudPlatform/google-cloud-cpp#610]
Currently `InstanceAdminEmulator` does not handle cluster properly for `CreateInstance` and `DeleteInstance` call., 

The behavior needs to be changed as follows
a. `CreateInstance` must add cluster associated with instance to `clusters_` collection. 
b. `DeleteInstance` must delete clusters associated with instance from `clusters_` collection.

please see #596 for further reference.

**Comment by manish-qlogic** [comment]
@coryan ,
should we consider it as close?

**Comment by coryan** [comment]
Fixed by #696.
