### ISSUE TITLE
Bigtable: write quickstart, table admin and instance admin samples

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/google-cloud-cpp#615]
The CPP CBT client needs a standard set of samples:

- [ ]  Quickstart: Show how to create a client, and perform a read.  It's supposed to get a user up and running as quickly as possible.
- [x] Administer Instances
- [ ] Administer Tables

Node.js Bigtable examples are the canonical examples.  The examples are currently functionally complete, but have minor style issues.

Here's the [PR for the quickstart and table admin](https://github.com/googleapis/nodejs-bigtable/pull/139).  Here's the [PR for the instance admin](https://github.com/googleapis/nodejs-bigtable/pull/125).

**Comment by manish-qlogic** [comment]
@coryan 

Currently, if we go by node js example PR, it supports following methods
` instances.js run     Creates an Instance(type: PRODUCTION) and run basic instance-operations`
` instances.js dev-instance  Create Development Instance`
` instances.js del-instance  Delete the Instance`
` instances.js add-cluster   Add Cluster`
` instances.js del-cluster   Delete the Cluster`

Where as #456 has a extensive list of scenarios.

Should we need to create another file like `bigtable_samples_instance_admin.cc` to refer in the dox file ?
or 
add few more method in the bigtable_samples_instance_admin.cc, We might need to adjust the current markings and it may have impact on generated htmls.

Pleaes suggest!

**Comment by coryan** [comment]
I think you should follow the nodejs example.

cc: @sduskis in case I am wrong.

**Comment by jabubake** [comment]
@sduskis @coryan:

I'm not seeing a sample that is similar to:

https://github.com/googleapis/nodejs-bigtable/blob/master/samples/quickstart.js

This is required for the documentation here: 
https://cloud.google.com/bigtable/docs/reference/libraries

to showcase a simple read.

@billyjacobson @jefesaurus FYI

**Comment by coryan** [comment]
Reopening: I thought the hello world was the same thing as the quickstart.
