### ISSUE TITLE
Separate table admin and data samples.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#647]
Having examples for both `TableAdmin` and `Table` in the same program makes the examples more complicated, and makes it hard to refactor the functions like I did here:

https://github.com/coryan/google-cloud-cpp/blob/286b4cb9ca50fc2e79523aee205c43a71ff85192/storage/examples/storage_bucket_samples.cc#L59

**Comment by sduskis** [comment]
This is a duplicate of #615
