### ISSUE TITLE
Minimal class to work with service_account credentials

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#656]
Implement a class that can parse the key file downloaded from a service account and create an access token from that.  The first version does not need to refresh the access token, or do anything smart, just enough to get going.

**Comment by houglum** [comment]
Ack. Will begin work on this next week.

**Comment by houglum** [comment]
Fixed with PR #766.  Many, many thanks to @coryan and @theacodes for the C++/OAuth knowledge and quick reviews.
