### ISSUE TITLE
Optimize CreateInstance and DeleteInstance in instance_admin_emulator.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#697]
As explained here:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/696#discussion_r194237018

and here:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/696#discussion_r194236910

there are some minor optimizations for the emulator.

**Comment by manish-qlogic** [comment]
@coryan 

for https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/696#discussion_r194237018, following [link](https://en.cppreference.com/w/cpp/algorithm/remove) suggests that `std::remove_if` cannot be used for `std::map`.

**Comment by coryan** [comment]
Yup, I forgot about the problems with `std::remove_if` and `std::map::erase`.  Bummer.

You can also do something like:

```C++
// First the first element that is >= than prefix, elements that share a prefix appear in order in the map,
// starting from the one that starts with *exactly* the prefix.
auto begin = clusters_.lower_bound(prefix);
while (begin != clusters_.end() and begin.first.find(prefix) == 0) {
  // Erase the element, erase() returns the next element in the map.
  begin = clusters_.erase(begin);
}
```

Which at least is `O(logN)` + K` instead of `K*O(logN)`.

It should also be possible to do something like this:

```C++
std::string prefix = ...;
std::string prefix_range_end = ...; // we have functions for this in RowRange.

// TODO() - coryan is probably wrong about the combination of upper/lower bounds here.
auto begin = clusters_.lower_bound(prefix);
auto end = clusters_.upper_bound(prefix_successor);
clusters_.erase(begin, end);
```
