### ISSUE TITLE
Publish C++ development style guidelines

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/google-cloud-cpp#70]
We are implicitly following parts of the [Google C++ style guide](https://google.github.io/styleguide/cppguide.html), but as we are taking some departures from it (e.g., exceptions, user-defined literals, etc.), we should do one of the following:

* publish a complete style guide on what features we will or won't use, OR
* publish a style guide that's a diff based on the Google C++ style guide

At the very least, we should clarify that we're using only what's available in C++11 and Abseil. Other questions might be around what can be brought in from other third-party libraries, e.g., [Boost](https://google.github.io/styleguide/cppguide.html#Boost), which the Google C++ style guide also has a section on.

Without such clarification, it's unclear what contributors can use for development and what they can't (or at least, shouldn't).

**Comment by coryan** [comment]
Made sure the style guide covers:
[] Which files are included with `<foo.h>` vs. `"foo.h"`
[] When is it necessary to root namespaces, i.e. `::testing` vs. `testing`, or `::google`.
