### ISSUE TITLE
Determine if OpenCensus would require API changes

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#712]
At the end of this issue we will have implemented a small prototype that uses OpenCensus C++ for the Bigtable Client.  The goals of this prototype are:

- Show how to use OpenCensus for a really simple client.
- Determine if any changes in the library are needed to share spans for rpcs that retry the same logical operation.
- Determine if any changes in the API are needed for applications that want to create spans that include multiple Bigtable operations.

The prototype can make simplifying assumptions, for example:

- OpenCensus only compiles with Bazel, so this prototype can limit itself to Bazel builds too.
- The prototype does not need to become part of the CI builds.

The goal is to reduce risk of future changes to the API.

cc: @sduskis for any additional comments.

**Comment by coryan** [comment]
> Show how to use OpenCensus for a really simple client.

I created a prototype for this here:

https://github.com/coryan/google-cloud-cpp/blob/f05d76066e480fa996d53df22052fd86458df1d0/google/cloud/bigtable/examples/bigtable_opencensus.cc#L47

Some good news: it is possible to compile the bigtable client with gRPC and OpenCensus, it requires changing the version of gRPC: the client compiles with v1.10.x by default, OpenCensus support is part of v1.14.x (at this point "upcoming", no release has been cut yet).

More good news: with very little effort the traces are exported to `stdout` and/or stackdriver.

> Determine if any changes in the library are needed to share spans for rpcs that retry the same logical operation.

Yes.  To annotate all the retry RPCs for the same logical operation requires changes in the code, here is an example of how to create a Span:

https://github.com/census-instrumentation/opencensus-cpp/blob/893e0835a45d749221f049d0d167e157b67b6d9c/examples/helloworld/helloworld.cc#L92

That code would need to be `#ifdef/#endif` protected because OpenCensus **only** compiles with Bazel (and gRPC **only** supports it with Bazel).

> Determine if any changes in the API are needed for applications that want to create spans that include multiple Bigtable operations.

Apparently not.

----

@sduskis I think we can merge that code and then close this issue.  Thoughts?

@ghaisa @mbrukman FYI.

**Comment by sduskis** [comment]
+1 for merging.

**Comment by sduskis** [comment]
@jabubake, is there someone that can review this?

**Comment by jabubake** [comment]
@sduskis : can you open a PR with that prototype code ? I'd like us to make sure that if a developer decides to use it, they understand the risks, any performance impacts. I am not very clear on the limiting to Bazel builds scenario and how that impacts developers.

**Comment by sduskis** [comment]
@jabubake, I think that I added that comment to the wrong PR.  This PR will be safe for non-Bazel users, and should be fine for those who do use it.

**Comment by sduskis** [comment]
The answer that this is not a beta blocker.
