### ISSUE TITLE
Consider using StrongType<> for arguments of similar type.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#724]
Many of our constructors will look like this:

```C++
Foo::Foo(std::string bucket_name, std::string object_name, ...)
```

The problem is that it is too easy to use those in the wrong order, as in `Foo("my-object", "my-bucket")`. We should consider using the strong type idiom to turn that into:

```C++
Foo::Foo(BucketName bucket_name, ObjectName object_name);
```

where `BucketName` and `ObjectName` require explicit construction from `std::string`.  There is a class in the Bigtable libraries for this already.  It is also trivial to implement as:

```C++
struct BucketName { std::string value; };
```

Application developers can use `BucketName{"my-bucket"}` to create one of these things.

**Comment by coryan** [comment]
cc: @houglum what do you think?

**Comment by houglum** [comment]
This seems a little too "hand-holdy" to me, personally... at least with the provided example.  I think in the scenarios where we have to pass in a lot of primitives that could be easily confused/swapped, we should instead require a struct that serves as a wrapper for those attribtues. A good example is the PatchObject method in the C# API:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/722f8df67515e201adb06d2d504162dae2a15df5/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/PatchObjectTest.cs#L42

...where something that requires the bucket name and object name to identify the object might as well just accept an ObjectMetadata type that contains those attributes.

**Comment by houglum** [comment]
This seems a little too "hand-holdy" to me, personally... at least with the provided example.  I think in the scenarios where we have to pass in a lot of primitives that could be easily confused/swapped, we should instead require a struct that serves as a wrapper for those attribtues. A good example is the PatchObject method in the C# API:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/722f8df67515e201adb06d2d504162dae2a15df5/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.IntegrationTests/PatchObjectTest.cs#L42

...where something that requires the bucket name and object name to identify the object might as well just accept an ObjectMetadata type that contains those attributes.

**Comment by coryan** [comment]
We considered it and decided against it. Closing.
