### ISSUE TITLE
Revisit definition of IsTransientError for bigtable::RPCRetryPolicy.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#741]
The definition includes `grpc::StatusCode::OK` as a possible transient error, which is weird. That was defensive programming when all this code was originally created, should be cleaned up.

**Comment by manish-qlogic** [comment]
@coryan 

As far as I understood, the cleanup would include
1.  Changing definition of [SafeGrpcRetry::IsTransientFailure](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/05bab87035440301fc3f600596f8e627961ea614/google/cloud/bigtable/rpc_retry_policy.h#L33) to

```
  static inline bool IsTransientFailure(grpc::StatusCode code) {
    return code == grpc::StatusCode::ABORTED or code == grpc::StatusCode::UNAVAILABLE or
           code == grpc::StatusCode::DEADLINE_EXCEEDED;
}
```
2. Changing definition of [SafeGrpcRetry::IsPermanentFailure](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/05bab87035440301fc3f600596f8e627961ea614/google/cloud/bigtable/rpc_retry_policy.h#L43) to
```
  static inline bool IsPermanentFailure(grpc::Status const& status) {
    return not IsOk(status) && not IsTransientFailure(status);
}
```
Is there any other piece of code or class that we need to investigate with this task?

**Comment by coryan** [comment]
I think that is it.
