### ISSUE TITLE
Implement integration test for ReadRow() against the Cloud Bigtable Emulator

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#76]
At this end of this task we will have an integration test for `Table::ReadRow()` against the Cloud Bigtable Emulator.  Look at #74 for inspiration.

**Comment by hemant-qlogic** [comment]
To implement integration test cases for this function, I think following way could be used.
For Method RowReader ReadRows(RowSet row_set, Filter filter) there is already implementation in bigtable::client::testing::table_integration_test.cc as ReadRows(bigtable::Table& table, bigtable::Filter filter). Similarly I will implement other two methods to use the functions RowReader ReadRows(RowSet row_set, std::int64_t rows_limit, Filter filter), std::pair<bool, Row> ReadRow(std::string row_key, Filter filter) and write the integration test case in one of the integration tests i.e. admin_integration_test.cc or data_integration_test.cc or mutation_integration_test.cc
is it ok?

**Comment by coryan** [comment]
> To implement integration test cases for this function, I think following way could be used.

> For Method `RowReader ReadRows(RowSet row_set, Filter filter)` there is already implementation in
> `bigtable::client::testing::table_integration_test.cc` as 
> `ReadRows(bigtable::Table& table, bigtable::Filter filter)`.

That is correct.

> Similarly I will implement other two methods

nit: C++ does not have methods, it has member functions.

> to use the functions `RowReader ReadRows(RowSet row_set, std::int64_t rows_limit, Filter filter)`,

Please do not test that function, as you noted there are some (incomplete) tests for it already, and @DanielMahu is working on completing these tests in #77. 

>  `std::pair<bool, Row> ReadRow(std::string row_key, Filter filter)`

Yes, you need to implement an integration test for this.

> and write the integration test case in one of the integration tests i.e. `admin_integration_test.cc`
> or `data_integration_test.cc` or `mutation_integration_test.cc`

Please include your new tests in `data_integration_test.cc` as new test cases (i.e. new `TEST_F()` functions).  When you implement these integration tests make sure you test both the case where the row exists and the case where the row does not exist.

Please let me know if my comments make sense.

nit: that paragraph could have used better formatting, a bit hard to read with everything in one wall of text+code.

**Comment by hemant-qlogic** [comment]
PTAL
Added new test case for row does not exist
