### ISSUE TITLE
Implement Object::Compose()

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#811]
This is a wrapper around [Objects: compose](https://cloud.google.com/storage/docs/json_api/v1/objects/compose).  The member function prototype should be similar to:

```C++
struct ComposeSource {
  std::string name;
  long generation;
  IfGenerationMatch if_generation_match;
};

class Client { public: 
ObjectMetadata Compose(std::string destination_bucket, std::string destination_object,
     std::vector<ComposeSource> const& sources,
     optional<ObjectMetadata> destination_metadata,
     Parameters&&... parameters);
};
```

This task is completed when:

- [ ] The new API has been added to Client.
- [ ] The new API has a completed doxygen comment block.
- [ ] There is a unit test for this API that checks the function works in an easy case.
- [ ] There is a unit test for this API that checks retries work correctly.
- [ ] There is a unit test for this API that checks errors are reported correctly.
- [ ] The uni tests run in the CI builds.
- [ ] There is an integration test for this API that runs against the emulator and against the GCS service.
- [ ] There is a code snippet showing how to use the API.
- [ ] The code snippet and the integration tests run in the CI builds.

**Comment by frankyn** [comment]
@coryan short update: given current time, I'll pick up this operation up next week. If you need to retriage I understand, just wanted to give a heads-up.

**Comment by coryan** [comment]
There is plenty of other work to do, no worries.  If we run out of things to do (HA!) and we are close to the end of the quarter I might have a different opinion.

**Comment by frankyn** [comment]
haha sounds good thanks @coryan!

**Comment by coryan** [comment]
Hey, I was wrong.  [`Objects: rewrite`](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) is the one that has complicated update semantics.  `Objects: compose` should be fairly straightforward.

**Comment by frankyn** [comment]
sg, thanks for clarifying.
