### ISSUE TITLE
Document order of cells returned by ReadRows() within a row.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#82]
I cannot find clear documentation of what the "first N" RowFilter actually would skip.  The documentation most likely exist, I just cannot find it.

Obvious it is the first N cells, but what is the order of the cells within a row?  The natural assumption is that cells are returned in the order defined by the column families, and then the column qualifiers within a column family, and then the timestamps within each column.  That is probably true, but I cannot find any docs saying that and it is better if I document that assumption.

This issue is here to find the right documentation (it must exist I just could not find it), link it from here and then update the documentation for the `bigtable::Filter` creation functions if the assumptions I made were wrong.

**Comment by coryan** [comment]
@sduskis or @mbrukman before I search for more documentation, can you point me to a doc explaining the order of cells within a row?  Thanks.

**Comment by sduskis** [comment]
I put some thoughts about it here
<https://docs.google.com/a/google.com/document/d/1DGoSGBl0_EzdMPy1p3A8pgFVS31jmemQb2DflUsycdI/edit?usp=sharing>
.

At a high level, ordering is as follows:

   - familly (ordered by some internal ID, not lexicographic)
   - qualifier (lexicographic)
   - timestamp (reverse order - latest is first)

-Solomon


Solomon Duskis |  Google Cloud Bigtable Tech Lead |  sduskis@google.com |
914-462-0531

**Comment by coryan** [comment]
Thanks @sduskis!  Is the internal ID of the family the same across all rows?

**Comment by sduskis** [comment]
That's an interesting question.  For now, assume that the family ordering may change across rows.
