### ISSUE TITLE
Decide what is the right behavior when creating "invalid" filters.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#84]
Some of the functions to create filters can produce non-sensical filters, for example, you can call `bigtable::Filter::Latest(-1)`.  Most likely that fails on the server side (does it? the proto documentation does not say), so maybe we should check in the client side and raise an exception.

One could argue that it is Okay though, the function did as requested, it is beyond's the client library's ability to check if your filters are semantically sensible.

Even if we decide to allow such filters to be created, we should document the effect of setting up filters with strange values.

This is a dependency for #30.

**Comment by coryan** [comment]
@sduskis any thoughts on what should we do when the filter builders are given semantically invalid data?

@sduskis or @mbrukman I cannot find documentation about what is the  behavior in the server when given semantically invalid values to a filter, specifically:

* `cells_per_column_limit_filter` with n  <  0
* `cells_per_row_limit_filter` with n < 0
* `cells_per_row_offset_filter` with n < 0

I think the following filters simply match (or should match) nothing, and going to assume that.

* `value_range_filter` with end < start
* `timestamp_range_filter` with end < start
* `column_range_filter` with end_qualifier < start_qualifier.

Is there a good place to enter these as bugs to the proto documentation?

**Comment by mbrukman** [comment]
@sduskis, @garye or @DanielMahu would be best-positioned to answer the question in [this comment](https://github.com/GoogleCloudPlatform/google-cloud-cpp/issues/84#issuecomment-350466334).

**Comment by coryan** [comment]
For what is worth, I wrote integration tests to check how the server behaves, so far I have found:

* `cells_per_column_limit_filter` with n < 0: server rejects the request with `grpc::StatusCode::INVALID_ARUMENT.
* `cells_per_row_limit_filter` with n < 0: server rejects the request with `grpc::StatusCode::INVALID_ARGUMENT.
* `cells_per_row_offset_filter` with n < 0: server rejects the request with `grpc::StatusCode::INVALID_ARGUMENT.
* `row_sample_filter` with probability outside the `(0.0, 1.0)` range is rejected with `grpc::StatusCode::INVALID_ARGUMENT.  The documentation says that the allowed range is `[0.0, 1.0]` for what is worth.

I still do not know where to file bugs against the protos.  It seems wrong to file an issue against the client libraries.  Thoughts?

**Comment by mbrukman** [comment]
@coryan wrote:

> any thoughts on what should we do when the filter builders are given semantically invalid data?

I'm all for providing error messages sooner rather than later (so giving good feedback on invalid arguments) — just getting `INVALID_ARGUMENT` is much later, and I'm not sure if it comes with a good error message that says what's wrong and how to fix it.

However, I consider it a "nice to have" and not a critical feature, so don't prioritize it higher than core functionality (i.e., MVP client).

Also, I'm curious what @sduskis, @garye, @DanielMahu, and @igorbernstein2 think.

> I still do not know where to file bugs against the protos. It seems wrong to file an issue against the client libraries. Thoughts?

File a bug internally (I'll contact you with more details) or just send a CL to update the proto comments; once updated internally (authoritative source), the proto files will be synced to GitHub.

**Comment by coryan** [comment]
I have created #148 for a post-MVP enhancement, we can close it with `wontfix` if we think it is a bad idea later.  I am going to document what happens with invalid filter values (in the `bigtable/client/filters.h` header), and then close this bug.
