### ISSUE TITLE
Simplify / Refactor google::cloud::storage::DefaultClient

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#862]
## Background

Writing a new API for the Google Cloud Storage client library requires touching multiple classes. One of these classes is the `google::cloud::storage::internal::DefaultClient`, which uses a template parameter for dependency injection:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/32b4beb0bd5fee994d850e1e5748d1a1dba46391/google/cloud/storage/internal/default_client.h#L34

The idea was to write unit tests for this class using a `MockHttpRequest` object, which would allow us to verify the class was using the `CurlRequest` object correctly, without having to write an integration test. But we have to write integration tests anyway, otherwise we do not know if the code works correctly against the service. And we have to write sample snippets that also run against the service.  Moreover, to speed up the cycle and improve coverage we have since implemented a python testbench to support integration tests.

## Overview

The proposal is to remove this class and replace it with something like this:

```C++
class CurlClient : public RawClient { public:
```

This class would not be unit-testable, because it will create concrete `CurlRequest` objects (and other `libcurl` wrapper objects if needed, but that is the subject for another document).

The class will be tested as part of the integration tests, which we are writing anyway, so it is a net savings in simplicity and coding effort for the same feature and code coverage.

### Non-goals
There are many other simplifications that we should implement to make it easier to implement new APIs in the library, those are outside the scope of this bug.

**Comment by houglum** [comment]
SGTM.
