### ISSUE TITLE
Default channel pool size should be based on CPU count

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#871]
The default channel pool size should use `std::thread::hardware_concurrency()` to auto configure the channel pool.

**Comment by sduskis** [comment]
Java uses 4:1 channels:cpu

**Comment by manish-qlogic** [comment]
@coryan 

As per the [link](https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency),  `std::thread::hardware_concurrency()` value should be considered only a hint. Its value can be 0 if the value is not well defined or not computable (compiler dependent)


so should we consider this logic during `ClientOptions` construct,
1. Check and set connection_pool_size to 4 times `std::thread::hardware_concurrency()` for a non zero value.
2. if  `std::thread::hardware_concurrency()` is zero then default connection_pool_size to BIGTABLE_CLIENT_DEFAULT_CONNECTION_POOL_SIZE.

**Comment by coryan** [comment]
@manish-qlogic that all SGTM, thanks for checking.
