### ISSUE TITLE
Make a pass removing 'using namespace' directives.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#873]
We should avoid `using namespace` in favor of specific `using blah::baz::Foo` or simply using the name explicitly.

**Comment by houglum** [comment]
I'll do this work -- pretty trivial and helps with readability reviews :)

**Comment by houglum** [comment]
Done with #908.  coryan@ filed #910 to track enforcing this in future commits.
