### ISSUE TITLE
[QUESTION] Stackdriver Monitoring API - C++

### ISSUE THREAD

**Issue by pcariel** [GoogleCloudPlatform/google-cloud-cpp#912]
Good evening dear.
I am building an application in gRPC C ++, I would like to be able to adapt Stackdriver to my project, is there an example which can do this?
regards

**Comment by coryan** [comment]
Have you looked at [Open Census](https://opencensus.io/), they have [C++ libraries](https://github.com/census-instrumentation/opencensus-cpp/). And I understand those include exporting metrics from your application.

**Comment by coryan** [comment]
@pcariel I assume we answered your question, if not, please feel free to reopen.
