### ISSUE TITLE
Unpin vcpkg version for AppVeyor builds

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#946]
For many reasons the latest and greatest packages do not work for us.  This is a reminder (with an accompanying TODO "soon") to unpin the vcpkg version.

**Comment by coryan** [comment]
Sent https://github.com/Microsoft/vcpkg/pull/3995 to upgrade the protobuf version, assuming that is accepted we can unpin the vcpkg version in our CI builds.

**Comment by ras0219-msft** [comment]
JFYI, thanks for the PR and here's a pingback that it has been merged :)
