### ISSUE TITLE
Reportedly idle channels are closed after minutes in the Bigtable C++ Client.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#952]
We need to write some tests to document the behavior of the client library (and gRPC) when channels are left idle for a long time.  Meaning 10 minutes or 1/2 hour.

Reportedly gRPC (or GFE or something) closes the connection and that results in a user-visible error message.

We should test with both an idle connection with no work pending, and with a scan (aka ReadRows()) where we receive a few rows and then the client pauses for many minutes.

It is too early to tell if the Bigtable library is doing something wrong here, just need to understand the current behavior and then decide if it is desirable.

**Comment by coryan** [comment]
This is the error one of our users got:

```
UnauthenticatedError (see above for traceback): Error reading from Cloud Bigtable: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (Details: )
```

It seems that leaving a session idle for very long (probably 1 hour or more) until the OAuth token expires does not recover gracefully. We should troubleshoot this.

**Comment by roopak-qlogic** [comment]
Tried to reproduced above user error, using  following:
1. written small integration test, for listclusters against production (grass-clump-4790), where listclusters API called two times with interval of 10 min  and 35 min, and seems working fine.
2.   executed  RPC call for listclusters two times with interval of 10 min  and 35 min, with updating of nox listclusters  API, and this time I got  exception 4=DEADLINE_EXCEEDED.
please let me know, if I am going in wrong direction for reproducing the issue.

**Comment by coryan** [comment]
In general, I think you are in the right direction.  Why ListClusters btw?  Nothing wrong with it, just a bit obscure...

I do not believe the `nox` (you mean `noex`, right?) has any bearing on this bug.  That seems like a red herring.

I take your test is something like:

```C++
instance_admin.ListClusters(...);
std::this_thread::sleep(10m);
instance_admin.ListClusters(...);
std::this_thread::sleep(35m);
instance_admin.ListClusters(...);
```

Did I get that right?  If so, please change the intervals to 40m and 70m.

**Comment by roopak-qlogic** [comment]
instance_admin_->ListClusters();
std::this_thread::sleep_for(2400_s);
auto clusters2 = instance_admin_->ListClusters();
std::this_thread::sleep_for(4200_s);
auto clusters = instance_admin_->ListClusters();

**Comment by roopak-qlogic** [comment]
I tried to reproduce using ReadRows as below, but not able to reproduce.
Also I putted my test code in saved mode, Just for reference, that am i followed the right steps.
https://github.com/GoogleCloudPlatform/google-cloud-cpp/compare/master...roopak-qlogic:Issue-952_testing?expand=1
Creating a table -> Writing 20 Row -> Reading 4 Row -> Waiting for : 2400 second -> Reading next 3 Row -> Waiting for : 4200 second -> Reading next 10 Row -> Deleting table -> Done

Above steps I used for 5400 seconds also

**Comment by coryan** [comment]
Thanks for researching this problem. Seems like it is more complicated than just the C++ client and gRPC. Let's close it for now until we have more information.
