### ISSUE TITLE
Create personal access token to push Doxygen docs to github.io

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-cpp#97]
Please create a [personal access token](https://github.com/settings/tokens) with the right permissions ([link](https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token)) and save it as a secret key in the travis [settings](https://travis-ci.org/GoogleCloudPlatform/google-cloud-cpp/settings) for our project.

This should automatically push the documentation on the next build from the `master` branch.

**Comment by coryan** [comment]
Ping.

**Comment by mbrukman** [comment]
I've been thinking about this, and I'm a bit concerned about the security aspects of this. By adding a Travis-encrypted GitHub token into our `.travis.yml` as an environment variable, given that we run Travis CI on every PR, any user will be able to submit a PR, where they can run an arbitrary script and reference that env var and have the ability to do just about anything (either on this, or any other repo) as the owner of the GitHub auth token.

They can also just `echo` the token to `stdout` (which will be visible on Travis), copy that token, and automate any number of actions using that token until it's discovered, possibly causing quite a bit of damage in the meantime (some recoverable, some possibly not).

Maybe I'm paranoid, but that makes me nervous.

I'd much rather:

* update the docs manually, if infrequently (e.g., weekly/monthly)
* update the docs automatically, using a private process (cron job?) without posting the access token

**Comment by coryan** [comment]
Travis does not provide the secret tokens to PRs for this reason.  Also Travis filters out all the secret tokens from the output.  So for example if you set `MY_SECRET` to `a-public-value`, then `a-public-value` will not appear in the output, even if it is printed from `A_NON_SECRET_VARIABLE`.

The risk is that we accept a PR that secretly steals the token away.

**Comment by coryan** [comment]
For more details: https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings

In particular:

> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

**Comment by coryan** [comment]
And this is also relevant:

https://blog.travis-ci.com/2017-05-08-security-advisory

**Comment by coryan** [comment]
Per our discussion, we agreed to create a bot account with limited privileges to push into this repo. 

I have created:

https://github.com/google-cloud-cpp-bot

The secret for this account is shared with you.  You are also invited to the email list that receives emails for that account.  I think you need to add the account to the repository with enough privileges to push code.  Then we need to create a personal access token for the bot account and add that token to Travis.

**Comment by coryan** [comment]
I have enough privileges to do this myself now.

**Comment by coryan** [comment]
Fixed: https://googlecloudplatform.github.io/google-cloud-cpp/
